/*------------------------------------------*/
USE GD2C2015
GO
/*------------------------------------------*/

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='THE_CVENGERS')

BEGIN

EXEC ('CREATE SCHEMA [THE_CVENGERS] AUTHORIZATION [gd]')

END

GO

create table [THE_CVENGERS].FECHA(
	FECHA_ID numeric(18,0) identity primary key,
	FECHA_RECIBIDA DATETIME,
	FECHA_REFERENCIA DATETIME
)

CREATE TABLE [THE_CVENGERS].ROL(
	ROL_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	ROL_NOMBRE NVARCHAR(100) unique NOT NULL,
	ROL_ESTADO BIT default 1 NOT NULL
)
GO

CREATE TABLE [THE_CVENGERS].FUNCIONALIDAD(
	FUNC_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	FUNC_NOMBRE NVARCHAR(100) NOT NULL,
	FUNC_DESCRIPCION NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE [THE_CVENGERS].FUNCIONXROL(
	FXR_ROL_ID NUMERIC(18,0) NOT NULL,
	FXR_FUNC_ID NUMERIC(18,0) NOT NULL,
	PRIMARY KEY(FXR_ROL_ID, FXR_FUNC_ID),
	CONSTRAINT FK_FXR_1 FOREIGN KEY (FXR_ROL_ID) REFERENCES [THE_CVENGERS].ROL (ROL_ID),                             
	CONSTRAINT FK_FXR_2 FOREIGN KEY (FXR_FUNC_ID) REFERENCES [THE_CVENGERS].FUNCIONALIDAD (FUNC_ID)
)
GO

CREATE TABLE [THE_CVENGERS].USUARIO(
	USR_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	USR_FALLIDOS NUMERIC (18,0) default 0,
	USR_USERNAME NVARCHAR(100) UNIQUE NOT NULL,
	USR_PASS VARCHAR(100) default hashbytes('SHA2_256', 'w23e') NOT NULL,
	USR_ESTADO BIT default 1 NOT NULL,
)
GO

CREATE TABLE [THE_CVENGERS].ROLXUSUARIO(
	ROLXUSUARIO_USUARIO NUMERIC(18,0),
	ROLXUSUARIO_ROL NUMERIC(18,0),
	PRIMARY KEY (ROLXUSUARIO_USUARIO, ROLXUSUARIO_ROL),
	CONSTRAINT FK_ROLXUSUARIO_1 FOREIGN KEY (ROLXUSUARIO_USUARIO) REFERENCES [THE_CVENGERS].USUARIO (USR_ID),
	CONSTRAINT FK_ROLXUSUARIO_2 FOREIGN KEY (ROLXUSUARIO_ROL) REFERENCES [THE_CVENGERS].ROL (ROL_ID)
)
GO


CREATE TABLE [THE_CVENGERS].CIUDAD(
	CIUDAD_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	CIUDAD_NOMBRE NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE [THE_CVENGERS].FABRICANTE(
	FABRICANTE_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	FABRICANTE_NOMBRE NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE [THE_CVENGERS].SERVICIO(
	SERVICIO_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	SERVICIO_PORCENTAJE NUMERIC(18,2) NOT NULL,
	SERVICIO_NOMBRE NVARCHAR(100) NOT NULL
)
GO


CREATE TABLE [THE_CVENGERS].TIPO_TARJETA(
	TIPO_TARJETA_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	TIPO_TARJETA_DETALLE NVARCHAR(18) NOT NULL
)
GO

CREATE TABLE [THE_CVENGERS].CUOTASXTARJETA(
	CUOTASXTARJETA_TIPO NUMERIC(18,0) NOT NULL,
	CUOTASXTARJETA_CUOTAS NUMERIC(2,0) NOT NULL,
	PRIMARY KEY (CUOTASXTARJETA_TIPO, CUOTASXTARJETA_CUOTAS),
	CONSTRAINT FK_CUOTASXTARJETA_1 FOREIGN KEY (CUOTASXTARJETA_TIPO) REFERENCES [THE_CVENGERS].TIPO_TARJETA (TIPO_TARJETA_ID)
)
GO


CREATE TABLE [THE_CVENGERS].CLIENTE(
	CLIENTE_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	CLIENTE_NOMBRE NVARCHAR(100) NOT NULL,
	CLIENTE_APELLIDO NVARCHAR(100) NOT NULL,
	CLIENTE_DNI NUMERIC(18,0) NOT NULL,
	CLIENTE_DIR NVARCHAR(100) NOT NULL,
	CLIENTE_TELEFONO NUMERIC(18,0) NOT NULL,
	CLIENTE_MAIL NVARCHAR(100),
	CLIENTE_FECHA_NAC DATETIME NOT NULL
	
)
GO

CREATE TABLE [THE_CVENGERS].TARJETACREDITO(
	TARJETA_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	TARJETA_CLIENTE NUMERIC(18,0) NOT NULL,
	TARJETA_TIPO NUMERIC(18,0) NOT NULL,
	TARJETA_NRO NUMERIC(16,0) NOT NULL,
	TARJETA_COD_SEGURIDAD NUMERIC(18,0) NOT NULL,
	TARJETA_FECHA_VENCIMIENTO DATETIME NOT NULL,
	CONSTRAINT FK_TARJETA_1 FOREIGN KEY (TARJETA_TIPO) REFERENCES [THE_CVENGERS].TIPO_TARJETA (TIPO_TARJETA_ID),
	CONSTRAINT FK_TARJETA_2 FOREIGN KEY (TARJETA_CLIENTE) REFERENCES [THE_CVENGERS].CLIENTE (CLIENTE_ID)
)
GO

CREATE TABLE [THE_CVENGERS].COMPRA(
	COMPRA_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	COMPRA_USUARIO_ID NUMERIC (18,0),
	COMPRA_CLIENTE NUMERIC(18,0) NOT NULL,
	COMPRA_TARJETA NUMERIC(18,0),
	COMPRA_FORMA_DE_PAGO bit not null,
	COMPRA_FECHA DATETIME NOT NULL,
	COMPRA_MONTO NUMERIC(18,2) NOT NULL,
	COMPRA_CANTIDAD_DE_CUOTAS NUMERIC(18,0) not null,
	CONSTRAINT FK_COMPRA_4 FOREIGN KEY (COMPRA_USUARIO_ID) REFERENCES [THE_CVENGERS].USUARIO (USR_ID),
	CONSTRAINT FK_COMPRA_2 FOREIGN KEY (COMPRA_CLIENTE) REFERENCES [THE_CVENGERS].CLIENTE (CLIENTE_ID),
	CONSTRAINT FK_COMPRA_3 FOREIGN KEY (COMPRA_TARJETA) REFERENCES [THE_CVENGERS].TARJETACREDITO (TARJETA_ID)
)
GO


CREATE TABLE [THE_CVENGERS].AERONAVE(
	AERONAVE_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	AERONAVE_CANTIDAD_BUTACAS NUMERIC(18,0),
	AERONAVE_FECHA_DE_ALTA DATETIME,
	AERONAVE_FECHA_DE_BAJA DATETIME,
	AERONAVE_FABRICANTE_AVION NUMERIC(18,0) NOT NULL,
	AERONAVE_ESPACIO_ENCOMIENDAS NUMERIC(18,2) NOT NULL,
	AERONAVE_ESTADO BIT NOT NULL DEFAULT 1,
	AERONAVE_MATRICULA_AVION NVARCHAR(100) UNIQUE NOT NULL,
	AERONAVE_MODELO_AVION NVARCHAR(100) NOT NULL,
	AERONAVE_SERVICIO NUMERIC(18,0) NOT NULL,
	CONSTRAINT FK_AERONAVE_1 FOREIGN KEY (AERONAVE_FABRICANTE_AVION) REFERENCES [THE_CVENGERS].FABRICANTE (FABRICANTE_ID),
	CONSTRAINT FK_AERONAVE_2 FOREIGN KEY (AERONAVE_SERVICIO) REFERENCES [THE_CVENGERS].SERVICIO (SERVICIO_ID)
)
GO

CREATE TABLE [THE_CVENGERS].TALLER(
	TALLER_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	TALLER_AERONAVE_ID NUMERIC(18,0) NOT NULL,
	TALLER_FECHA_ENTRADA DATETIME,
	TALLER_FECHA_SALIDA DATETIME,
	CONSTRAINT FK_TALLER_1 FOREIGN KEY (TALLER_AERONAVE_ID) REFERENCES [THE_CVENGERS].AERONAVE (AERONAVE_ID)
)
GO

CREATE TABLE [THE_CVENGERS].RUTA(
    RUTA_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	RUTA_CODIGO NUMERIC(18,0) NOT NULL,
	RUTA_ORIGEN NUMERIC(18,0) NOT NULL,
	RUTA_DESTINO NUMERIC(18,0) NOT NULL,
	RUTA_PRECIO_BASE_POR_KILO NUMERIC(18,2) NOT NULL,
	RUTA_PRECIO_BASE_POR_PASAJE NUMERIC(18,2) NOT NULL,
	RUTA_ESTADO BIT DEFAULT 1,
	CONSTRAINT FK_RUTA_1 FOREIGN KEY (RUTA_ORIGEN) REFERENCES [THE_CVENGERS].CIUDAD (CIUDAD_ID),
	CONSTRAINT FK_RUTA_2 FOREIGN KEY (RUTA_DESTINO) REFERENCES [THE_CVENGERS].CIUDAD (CIUDAD_ID),
	CONSTRAINT CK_RUTA_1 CHECK(RUTA_DESTINO NOT LIKE RUTA_ORIGEN)
)
GO

CREATE TABLE [THE_CVENGERS].SERVICIOXRUTA(
	SERVICIOXRUTA_RUTA NUMERIC(18,0),
	SERVICIOXRUTA_SERVICIO NUMERIC(18,0),
	PRIMARY KEY (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO),
	CONSTRAINT FK_SERVICIOXRUTA_1 FOREIGN KEY (SERVICIOXRUTA_RUTA) REFERENCES [THE_CVENGERS].RUTA (RUTA_ID),
	CONSTRAINT FK_SERVICIOXRUTA_2 FOREIGN KEY (SERVICIOXRUTA_SERVICIO) REFERENCES [THE_CVENGERS].SERVICIO (SERVICIO_ID)
)
GO


CREATE TABLE [THE_CVENGERS].VIAJE(
	VIAJE_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	VIAJE_FECHA_SALIDA DATETIME NOT NULL,
	VIAJE_FECHA_LLEGADA DATETIME,
	VIAJE_FECHA_LLEGADA_ESTIMADA DATETIME NOT NULL,
	VIAJE_ESTADO BIT NOT NULL DEFAULT 1,
	VIAJE_AERONAVE NUMERIC(18,0) NOT NULL,
	VIAJE_RUTA NUMERIC(18,0) NOT NULL,
	CONSTRAINT FK_VIAJE_1 FOREIGN KEY (VIAJE_AERONAVE) REFERENCES [THE_CVENGERS].AERONAVE (AERONAVE_ID),
	CONSTRAINT FK_VIAJE_2 FOREIGN KEY (VIAJE_RUTA) REFERENCES [THE_CVENGERS].RUTA (RUTA_ID)
)
GO



CREATE TABLE [THE_CVENGERS].PASAJE(
    PASAJE_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	PASAJE_CODIGO_PASAJE NUMERIC(18,0) NOT NULL,
	PASAJE_CLI_ID NUMERIC(18,0) NOT NULL,
	PASAJE_VIAJE_ID NUMERIC(18,0) NOT NULL,
	PASAJE_COMPRA NUMERIC(18,0) NOT NULL,
	PASAJE_DEVOLUCION NUMERIC(18,0),
	CONSTRAINT FK_PASAJE_1 FOREIGN KEY (PASAJE_CLI_ID) REFERENCES [THE_CVENGERS].CLIENTE (CLIENTE_ID),
	CONSTRAINT FK_PASAJE_2 FOREIGN KEY (PASAJE_VIAJE_ID) REFERENCES [THE_CVENGERS].VIAJE (VIAJE_ID),
	CONSTRAINT FK_PASAJE_3 FOREIGN KEY (PASAJE_COMPRA) REFERENCES [THE_CVENGERS].COMPRA (COMPRA_ID),
	CONSTRAINT FK_PASAJE_4 FOREIGN KEY (PASAJE_DEVOLUCION) REFERENCES [THE_CVENGERS].DEVOLUCION (DEVOLUCION_ID)
)
GO

CREATE TABLE [THE_CVENGERS].BUTACA(

    BUTACA_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	BUTACA_NRO NUMERIC(18,0) NOT NULL,
	BUTACA_AERONAVE NUMERIC (18,0) NOT NULL,
	BUTACA_TIPO NVARCHAR(100) NOT NULL,
	BUTACA_PISO NUMERIC(18,0) NOT NULL,
	CONSTRAINT FK_BUTACA_1 FOREIGN KEY (BUTACA_AERONAVE) REFERENCES [THE_CVENGERS].AERONAVE (AERONAVE_ID),
)
GO

CREATE TABLE [THE_CVENGERS].ENCOMIENDA(
	ENCOMIENDA_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	ENCOMIENDA_CODIGO NUMERIC(18,0) NOT NULL,
	ENCOMIENDA_CLI_ID NUMERIC(18,0) NOT NULL,
	ENCOMIENDA_VIAJE_ID NUMERIC(18,0) NOT NULL,
	ENCOMIENDA_KG  NUMERIC(18,0) NOT NULL,
	ENCOMIENDA_COMPRA NUMERIC(18,0) NOT NULL,
	ENCOMIENDA_DEVOLUCION NUMERIC(18,0)
	CONSTRAINT FK_ENCOMIENDA_1 FOREIGN KEY (ENCOMIENDA_CLI_ID) REFERENCES [THE_CVENGERS].CLIENTE (CLIENTE_ID),
	CONSTRAINT FK_ENCOMIENDA_2 FOREIGN KEY (ENCOMIENDA_VIAJE_ID) REFERENCES [THE_CVENGERS].VIAJE (VIAJE_ID),
	CONSTRAINT FK_ENCOMIENDA_3 FOREIGN KEY (ENCOMIENDA_COMPRA) REFERENCES [THE_CVENGERS].COMPRA (COMPRA_ID),
	CONSTRAINT FK_ENCOMIENDA_4 FOREIGN KEY (ENCOMIENDA_DEVOLUCION) REFERENCES [THE_CVENGERS].DEVOLUCION (DEVOLUCION_ID)
)
GO

CREATE TABLE [THE_CVENGERS].BUTACAXVIAJE(
	BUTACAXVIAJE_VIAJE_ID NUMERIC(18,0) NOT NULL,
	BUTACAXVIAJE_BUTACA_ID NUMERIC(18,0) NOT NULL,
	BUTACAXVIAJE_PASAJE_ID NUMERIC(18,0),
	PRIMARY KEY (BUTACAXVIAJE_VIAJE_ID, BUTACAXVIAJE_BUTACA_ID),
	CONSTRAINT FK_BUTACAXVIAJE_1 FOREIGN KEY (BUTACAXVIAJE_BUTACA_ID) REFERENCES [THE_CVENGERS].BUTACA (BUTACA_ID),
	CONSTRAINT FK_BUTACAXVIAJE_2 FOREIGN KEY (BUTACAXVIAJE_VIAJE_ID) REFERENCES [THE_CVENGERS].VIAJE (VIAJE_ID),
	CONSTRAINT FK_BUTACAXVIAJE_3 FOREIGN KEY (BUTACAXVIAJE_PASAJE_ID) REFERENCES [THE_CVENGERS].PASAJE (PASAJE_ID)
)
GO

CREATE TABLE [THE_CVENGERS].DEVOLUCION(
	DEVOLUCION_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	DEVOLUCION_NUM_COMPRA NUMERIC(18,0),
	DEVOLUCION_FECHA DATETIME NOT NULL,
	DEVOLUCION_DESCRIPCION NVARCHAR(100),
	CONSTRAINT FK_DEVOLUCION_1 FOREIGN KEY (DEVOLUCION_NUM_COMPRA) REFERENCES [THE_CVENGERS].COMPRA (COMPRA_ID)
)
GO

CREATE TABLE [THE_CVENGERS].PRODUCTO(
	PRODUCTO_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	PRODUCTO_NOMBRE NVARCHAR(100) NOT NULL,
	PRODUCTO_MILLAS_NECESARIAS NUMERIC(18,2) NOT NULL,
	PRODUCTO_STOCK NUMERIC(18,0) NOT NULL
)
GO

CREATE TABLE [THE_CVENGERS].CANJE(
	CANJE_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	CANJE_CLIENTE NUMERIC(18,0) NOT NULL,
	CANJE_PROD NUMERIC(18,0) NOT NULL,
	CANJE_FECHA DATETIME NOT NULL,
	CANJE_CANTIDAD NUMERIC(18,0) NOT NULL,
	CONSTRAINT FK_CANJE_1 FOREIGN KEY (CANJE_PROD) REFERENCES [THE_CVENGERS].PRODUCTO (PRODUCTO_ID),
	CONSTRAINT FK_CANJE_2 FOREIGN KEY (CANJE_CLIENTE) REFERENCES [THE_CVENGERS].CLIENTE (CLIENTE_ID)
)
GO

CREATE TABLE [THE_CVENGERS].MILLA(
	MILLA_ID NUMERIC(18,0) IDENTITY PRIMARY KEY,
	MILLA_CLIENTE NUMERIC(18,0) NOT NULL,
	MILLA_GANADA NUMERIC(18,0) NOT NULL,
	MILLA_GASTADA NUMERIC(18,0) default 0,
	MILLA_FECHA_ACREDITACION DATETIME NOT NULL,
	CONSTRAINT FK_MILLA_1 FOREIGN KEY (MILLA_CLIENTE) REFERENCES [THE_CVENGERS].CLIENTE (CLIENTE_ID)
)
GO


CREATE PROCEDURE [THE_CVENGERS].INIC_CLIENTE
AS
BEGIN
INSERT INTO [THE_CVENGERS].CLIENTE (CLIENTE_APELLIDO,CLIENTE_DIR,CLIENTE_DNI,CLIENTE_FECHA_NAC,CLIENTE_MAIL,CLIENTE_NOMBRE,CLIENTE_TELEFONO)
SELECT DISTINCT Cli_Apellido,Cli_Dir,Cli_Dni,Cli_Fecha_Nac,Cli_Mail,Cli_Nombre,Cli_Telefono FROM GD2C2015.gd_esquema.Maestra -- ORDER BY Cli_Apellido, Cli_Nombre
END

GO

CREATE PROCEDURE [THE_CVENGERS].INIC_CIUDAD
AS
BEGIN
INSERT INTO [THE_CVENGERS].CIUDAD (CIUDAD_NOMBRE)
SELECT DISTINCT Ruta_Ciudad_Origen FROM GD2C2015.gd_esquema.Maestra
UNION
SELECT DISTINCT Ruta_Ciudad_Destino FROM GD2C2015.gd_esquema.Maestra
END
GO


CREATE PROCEDURE [THE_CVENGERS].INIC_FABRICANTE
AS
BEGIN
INSERT INTO [THE_CVENGERS].FABRICANTE (FABRICANTE_NOMBRE)
SELECT DISTINCT Aeronave_Fabricante FROM GD2C2015.gd_esquema.Maestra
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_SERVICIO
AS
BEGIN
INSERT INTO [THE_CVENGERS].SERVICIO (SERVICIO_NOMBRE, SERVICIO_PORCENTAJE)
SELECT DISTINCT Tipo_Servicio, round(AVG(((Pasaje_Precio/Ruta_Precio_BasePasaje)*100) - 100), 0) FROM GD2C2015.gd_esquema.Maestra WHERE Pasaje_Codigo <> 0 GROUP BY Tipo_Servicio
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_AERONAVE
AS
BEGIN
INSERT INTO [THE_CVENGERS].AERONAVE (AERONAVE_FABRICANTE_AVION, AERONAVE_ESPACIO_ENCOMIENDAS, AERONAVE_MATRICULA_AVION, AERONAVE_MODELO_AVION, AERONAVE_SERVICIO)
SELECT DISTINCT (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE FABRICANTE_NOMBRE = Aeronave_Fabricante), Aeronave_KG_Disponibles, Aeronave_Matricula, Aeronave_Modelo, (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = Tipo_Servicio) FROM GD2C2015.gd_esquema.Maestra

DECLARE @V2 NUMERIC(18,0),
		@V6 NVARCHAR(100)

DECLARE CURSOR_AVION CURSOR 
FOR SELECT AERONAVE_CANTIDAD_BUTACAS, AERONAVE_MATRICULA_AVION FROM AERONAVE
OPEN CURSOR_AVION
FETCH FROM CURSOR_AVION INTO @V2, @V6
WHILE @@FETCH_STATUS = 0
BEGIN
SET @V2 =(SELECT  MAX(Butaca_Nro) FROM GD2C2015.gd_esquema.Maestra WHERE Aeronave_Matricula = @V6 AND Butaca_Nro <> 0) + 1

UPDATE [THE_CVENGERS].AERONAVE
SET AERONAVE_CANTIDAD_BUTACAS = @V2
WHERE AERONAVE_MATRICULA_AVION = @V6

FETCH NEXT FROM CURSOR_AVION INTO @V2, @V6
END
CLOSE CURSOR_AVION
DEALLOCATE CURSOR_AVION

ALTER TABLE [THE_CVENGERS].AERONAVE
ALTER COLUMN AERONAVE_CANTIDAD_BUTACAS NUMERIC NOT NULL 


END
GO



CREATE PROCEDURE [THE_CVENGERS].INIC_RUTA
AS
BEGIN
INSERT INTO [THE_CVENGERS].RUTA (RUTA_CODIGO, RUTA_DESTINO, RUTA_ORIGEN, RUTA_PRECIO_BASE_POR_KILO, RUTA_PRECIO_BASE_POR_PASAJE)
SELECT DISTINCT a.Ruta_Codigo, (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Destino), (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Origen), (select top 1 b.Ruta_Precio_BaseKG from GD2C2015.gd_esquema.Maestra b where b.Ruta_Precio_BaseKG <> 0.00 and b.Ruta_Ciudad_Destino = a.Ruta_Ciudad_Destino and b.Ruta_Ciudad_Origen = a.Ruta_Ciudad_Origen), (select top 1 b.Ruta_Precio_BasePasaje from GD2C2015.gd_esquema.Maestra b where b.Ruta_Precio_BasePasaje <> 0.00 and b.Ruta_Ciudad_Destino = a.Ruta_Ciudad_Destino and b.Ruta_Ciudad_Origen = a.Ruta_Ciudad_Origen) FROM GD2C2015.gd_esquema.Maestra a
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_SERVICIOXRUTA
AS
BEGIN
INSERT INTO [THE_CVENGERS].SERVICIOXRUTA (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO)
SELECT DISTINCT (SELECT RUTA_ID FROM [THE_CVENGERS].RUTA R WHERE R.RUTA_DESTINO = (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Destino) AND R.RUTA_ORIGEN = (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Origen)), (SELECT S.SERVICIO_ID FROM [THE_CVENGERS].SERVICIO S WHERE S.SERVICIO_NOMBRE = A.Tipo_Servicio) FROM GD2C2015.gd_esquema.Maestra a
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_VIAJE
AS
BEGIN
INSERT INTO [THE_CVENGERS].VIAJE (VIAJE_FECHA_SALIDA, VIAJE_FECHA_LLEGADA, VIAJE_FECHA_LLEGADA_ESTIMADA, VIAJE_AERONAVE, VIAJE_RUTA)
SELECT DISTINCT FechaSalida, FechaLLegada, Fecha_LLegada_Estimada, (SELECT AERONAVE_ID FROM [THE_CVENGERS].AERONAVE WHERE AERONAVE_FABRICANTE_AVION = (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE Aeronave_Fabricante = FABRICANTE_NOMBRE) AND AERONAVE_ESPACIO_ENCOMIENDAS = Aeronave_KG_Disponibles AND AERONAVE_MATRICULA_AVION = Aeronave_Matricula AND AERONAVE_MODELO_AVION = Aeronave_Modelo AND AERONAVE_SERVICIO = (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = Tipo_Servicio)), (SELECT RUTA_ID FROM [THE_CVENGERS].RUTA WHERE (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = Ruta_Ciudad_Destino) = RUTA_DESTINO AND (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = Ruta_Ciudad_Origen) = RUTA_ORIGEN) FROM GD2C2015.gd_esquema.Maestra
END 
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_BUTACA
AS 
BEGIN
INSERT INTO [THE_CVENGERS].BUTACA (BUTACA_NRO, BUTACA_PISO, BUTACA_TIPO, BUTACA_AERONAVE)
SELECT DISTINCT Butaca_Nro, Butaca_Piso, Butaca_Tipo, (SELECT AERONAVE_ID FROM [THE_CVENGERS].AERONAVE WHERE AERONAVE_FABRICANTE_AVION = (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE Aeronave_Fabricante = FABRICANTE_NOMBRE) AND AERONAVE_ESPACIO_ENCOMIENDAS = Aeronave_KG_Disponibles AND AERONAVE_MATRICULA_AVION = Aeronave_Matricula AND AERONAVE_MODELO_AVION = Aeronave_Modelo AND AERONAVE_SERVICIO = (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = Tipo_Servicio))  FROM GD2C2015.gd_esquema.Maestra
WHERE Butaca_Tipo <> '0'
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_COMPRA
AS
BEGIN
INSERT INTO [THE_CVENGERS].COMPRA (COMPRA_FECHA, COMPRA_MONTO, COMPRA_CLIENTE, COMPRA_FORMA_DE_PAGO, COMPRA_CANTIDAD_DE_CUOTAS)
SELECT DISTINCT (case when a.Pasaje_FechaCompra <> '1900-01-01 00:00:00.000' then a.Pasaje_FechaCompra else a.Paquete_FechaCompra end), (case when a.Pasaje_FechaCompra <> '1900-01-01 00:00:00.000' then a.Pasaje_Precio else a.Paquete_Precio end), (SELECT CLIENTE_ID FROM [THE_CVENGERS].CLIENTE WHERE CLIENTE_NOMBRE = Cli_Nombre AND CLIENTE_APELLIDO = Cli_Apellido AND CLIENTE_DIR = Cli_Dir AND CLIENTE_DNI = Cli_Dni AND CLIENTE_FECHA_NAC = Cli_Fecha_Nac AND CLIENTE_MAIL = Cli_Mail AND CLIENTE_TELEFONO = Cli_Telefono), 0, 1 FROM GD2C2015.gd_esquema.Maestra a
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_PASAJE
AS
BEGIN
INSERT INTO [THE_CVENGERS].PASAJE (PASAJE_CODIGO_PASAJE, PASAJE_CLI_ID, PASAJE_VIAJE_ID, PASAJE_COMPRA)
SELECT DISTINCT Pasaje_Codigo, (SELECT CLIENTE_ID FROM [THE_CVENGERS].CLIENTE WHERE CLIENTE_NOMBRE = Cli_Nombre AND CLIENTE_APELLIDO = Cli_Apellido AND CLIENTE_DIR = Cli_Dir AND CLIENTE_DNI = Cli_Dni AND CLIENTE_FECHA_NAC = Cli_Fecha_Nac AND CLIENTE_MAIL = Cli_Mail AND CLIENTE_TELEFONO = Cli_Telefono),(SELECT VIAJE_ID FROM [THE_CVENGERS].VIAJE WHERE VIAJE_AERONAVE = (SELECT AERONAVE_ID FROM [THE_CVENGERS].AERONAVE WHERE AERONAVE_FABRICANTE_AVION = (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE Aeronave_Fabricante = FABRICANTE_NOMBRE) AND AERONAVE_ESPACIO_ENCOMIENDAS = Aeronave_KG_Disponibles AND AERONAVE_MATRICULA_AVION = Aeronave_Matricula AND AERONAVE_MODELO_AVION = Aeronave_Modelo AND AERONAVE_SERVICIO = (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = Tipo_Servicio)) AND VIAJE_FECHA_LLEGADA = FechaLLegada AND VIAJE_FECHA_LLEGADA_ESTIMADA = Fecha_LLegada_Estimada AND VIAJE_FECHA_SALIDA = FechaSalida AND VIAJE_RUTA = (SELECT RUTA_ID FROM [THE_CVENGERS].RUTA WHERE (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = Ruta_Ciudad_Destino) = RUTA_DESTINO AND (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = Ruta_Ciudad_Origen) = RUTA_ORIGEN)), (SELECT COMPRA_ID FROM THE_CVENGERS.COMPRA WHERE COMPRA_FECHA = Pasaje_FechaCompra AND COMPRA_MONTO = Pasaje_Precio AND COMPRA_CLIENTE = (SELECT CLIENTE_ID FROM [THE_CVENGERS].CLIENTE WHERE CLIENTE_NOMBRE = Cli_Nombre AND CLIENTE_APELLIDO = Cli_Apellido AND CLIENTE_DIR = Cli_Dir AND CLIENTE_DNI = Cli_Dni AND CLIENTE_FECHA_NAC = Cli_Fecha_Nac AND CLIENTE_MAIL = Cli_Mail AND CLIENTE_TELEFONO = Cli_Telefono)) FROM GD2C2015.gd_esquema.Maestra
WHERE Pasaje_Codigo <> 0
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_ENCOMIENDA
AS
BEGIN
INSERT INTO [THE_CVENGERS].ENCOMIENDA (ENCOMIENDA_CODIGO, ENCOMIENDA_CLI_ID, ENCOMIENDA_VIAJE_ID, ENCOMIENDA_KG, ENCOMIENDA_COMPRA)
SELECT DISTINCT Paquete_Codigo, (SELECT CLIENTE_ID FROM [THE_CVENGERS].CLIENTE WHERE CLIENTE_NOMBRE = Cli_Nombre AND CLIENTE_APELLIDO = Cli_Apellido AND CLIENTE_DIR = Cli_Dir AND CLIENTE_DNI = Cli_Dni AND CLIENTE_FECHA_NAC = Cli_Fecha_Nac AND CLIENTE_MAIL = Cli_Mail AND CLIENTE_TELEFONO = Cli_Telefono), (SELECT VIAJE_ID FROM [THE_CVENGERS].VIAJE WHERE VIAJE_AERONAVE = (SELECT AERONAVE_ID FROM [THE_CVENGERS].AERONAVE WHERE AERONAVE_FABRICANTE_AVION = (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE Aeronave_Fabricante = FABRICANTE_NOMBRE) AND AERONAVE_ESPACIO_ENCOMIENDAS = Aeronave_KG_Disponibles AND AERONAVE_MATRICULA_AVION = Aeronave_Matricula AND AERONAVE_MODELO_AVION = Aeronave_Modelo AND AERONAVE_SERVICIO = (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = Tipo_Servicio)) AND VIAJE_FECHA_LLEGADA = FechaLLegada AND VIAJE_FECHA_LLEGADA_ESTIMADA = Fecha_LLegada_Estimada AND VIAJE_FECHA_SALIDA = FechaSalida AND VIAJE_RUTA = (SELECT RUTA_ID FROM [THE_CVENGERS].RUTA WHERE (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = Ruta_Ciudad_Destino) = RUTA_DESTINO AND (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = Ruta_Ciudad_Origen) = RUTA_ORIGEN)), Paquete_KG, (SELECT COMPRA_ID FROM THE_CVENGERS.COMPRA WHERE COMPRA_FECHA = Paquete_FechaCompra AND COMPRA_MONTO = Paquete_Precio AND COMPRA_CLIENTE = (SELECT CLIENTE_ID FROM [THE_CVENGERS].CLIENTE WHERE CLIENTE_NOMBRE = Cli_Nombre AND CLIENTE_APELLIDO = Cli_Apellido AND CLIENTE_DIR = Cli_Dir AND CLIENTE_DNI = Cli_Dni AND CLIENTE_FECHA_NAC = Cli_Fecha_Nac AND CLIENTE_MAIL = Cli_Mail AND CLIENTE_TELEFONO = Cli_Telefono)) FROM GD2C2015.gd_esquema.Maestra
WHERE Paquete_Codigo <> 0
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_BUTACAXVIAJE
AS
BEGIN
INSERT INTO [THE_CVENGERS].BUTACAXVIAJE(BUTACAXVIAJE_BUTACA_ID, BUTACAXVIAJE_VIAJE_ID, BUTACAXVIAJE_PASAJE_ID)
SELECT DISTINCT (SELECT BUTACA_ID FROM BUTACA WHERE BUTACA_NRO = a.Butaca_Nro AND BUTACA_PISO = a.Butaca_Piso AND BUTACA_TIPO = a.Butaca_Tipo AND BUTACA_AERONAVE = (SELECT AERONAVE_ID FROM [THE_CVENGERS].AERONAVE WHERE AERONAVE_FABRICANTE_AVION = (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE a.Aeronave_Fabricante = FABRICANTE_NOMBRE) AND AERONAVE_ESPACIO_ENCOMIENDAS = a.Aeronave_KG_Disponibles AND AERONAVE_MATRICULA_AVION = a.Aeronave_Matricula AND AERONAVE_MODELO_AVION = a.Aeronave_Modelo AND AERONAVE_SERVICIO = (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = a.Tipo_Servicio))), (SELECT VIAJE_ID FROM [THE_CVENGERS].VIAJE WHERE VIAJE_AERONAVE = (SELECT AERONAVE_ID FROM [THE_CVENGERS].AERONAVE WHERE AERONAVE_FABRICANTE_AVION = (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE a.Aeronave_Fabricante = FABRICANTE_NOMBRE) AND AERONAVE_ESPACIO_ENCOMIENDAS = a.Aeronave_KG_Disponibles AND AERONAVE_MATRICULA_AVION = a.Aeronave_Matricula AND AERONAVE_MODELO_AVION = a.Aeronave_Modelo AND AERONAVE_SERVICIO = (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = a.Tipo_Servicio)) AND VIAJE_FECHA_LLEGADA = a.FechaLLegada AND VIAJE_FECHA_LLEGADA_ESTIMADA = a.Fecha_LLegada_Estimada AND VIAJE_FECHA_SALIDA = a.FechaSalida AND VIAJE_RUTA = (SELECT RUTA_ID FROM [THE_CVENGERS].RUTA WHERE (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Destino) = RUTA_DESTINO AND (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Origen) = RUTA_ORIGEN)), (SELECT PASAJE_ID FROM PASAJE WHERE PASAJE_CODIGO_PASAJE = a.Pasaje_Codigo and PASAJE_CLI_ID = (SELECT CLIENTE_ID FROM [THE_CVENGERS].CLIENTE WHERE CLIENTE_NOMBRE = a.Cli_Nombre AND CLIENTE_APELLIDO = a.Cli_Apellido AND CLIENTE_DIR = a.Cli_Dir AND CLIENTE_DNI = a.Cli_Dni AND CLIENTE_FECHA_NAC = a.Cli_Fecha_Nac AND CLIENTE_MAIL = a.Cli_Mail AND CLIENTE_TELEFONO = a.Cli_Telefono) and PASAJE_VIAJE_ID = (SELECT VIAJE_ID FROM [THE_CVENGERS].VIAJE WHERE VIAJE_AERONAVE = (SELECT AERONAVE_ID FROM [THE_CVENGERS].AERONAVE WHERE AERONAVE_FABRICANTE_AVION = (SELECT FABRICANTE_ID FROM [THE_CVENGERS].FABRICANTE WHERE a.Aeronave_Fabricante = FABRICANTE_NOMBRE) AND AERONAVE_ESPACIO_ENCOMIENDAS = a.Aeronave_KG_Disponibles AND AERONAVE_MATRICULA_AVION = a.Aeronave_Matricula AND AERONAVE_MODELO_AVION = a.Aeronave_Modelo AND AERONAVE_SERVICIO = (SELECT SERVICIO_ID FROM [THE_CVENGERS].SERVICIO WHERE SERVICIO_NOMBRE = a.Tipo_Servicio)) AND VIAJE_FECHA_LLEGADA = a.FechaLLegada AND VIAJE_FECHA_LLEGADA_ESTIMADA = a.Fecha_LLegada_Estimada AND VIAJE_FECHA_SALIDA = a.FechaSalida AND VIAJE_RUTA = (SELECT RUTA_ID FROM [THE_CVENGERS].RUTA WHERE (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Destino) = RUTA_DESTINO AND (SELECT CIUDAD_ID FROM [THE_CVENGERS].CIUDAD WHERE CIUDAD_NOMBRE = a.Ruta_Ciudad_Origen) = RUTA_ORIGEN))) 
FROM GD2C2015.gd_esquema.Maestra a WHERE  a.Pasaje_FechaCompra <> '1900-01-01 00:00:00.000'
END
GO

CREATE PROCEDURE [THE_CVENGERS].INIC_MILLA
AS
BEGIN
INSERT INTO [THE_CVENGERS].MILLA(MILLA_CLIENTE, MILLA_GANADA, MILLA_FECHA_ACREDITACION)
SELECT PASAJE_CLI_ID, cast((((SELECT RUTA_PRECIO_BASE_POR_PASAJE 
						FROM THE_CVENGERS.RUTA
						WHERE RUTA_ID = (SELECT VIAJE_RUTA
										FROM THE_CVENGERS.VIAJE
										WHERE VIAJE_ID = PASAJE_VIAJE_ID)) + ((SELECT SERVICIO_PORCENTAJE/100
																				FROM THE_CVENGERS.SERVICIO
																				WHERE SERVICIO_ID = (SELECT AERONAVE_SERVICIO
																										FROM THE_CVENGERS.AERONAVE
																										WHERE AERONAVE_ID = (SELECT	VIAJE_AERONAVE
																																FROM THE_CVENGERS.VIAJE
																																WHERE VIAJE_ID = PASAJE_VIAJE_ID))) * (SELECT RUTA_PRECIO_BASE_POR_PASAJE 
																																										FROM THE_CVENGERS.RUTA
																																										WHERE RUTA_ID = (SELECT VIAJE_RUTA 
																																															FROM THE_CVENGERS.VIAJE
																																															WHERE VIAJE_ID = PASAJE_VIAJE_ID)))) /10) as int), (SELECT VIAJE_FECHA_LLEGADA	
																																																										FROM THE_CVENGERS.VIAJE
																																																										WHERE VIAJE_ID = PASAJE_VIAJE_ID)
																																									
FROM THE_CVENGERS.PASAJE
WHERE PASAJE_DEVOLUCION IS NULL
UNION ALL
SELECT ENCOMIENDA_CLI_ID, cast((((SELECT RUTA_PRECIO_BASE_POR_KILO * ENCOMIENDA_KG
						FROM THE_CVENGERS.RUTA
						WHERE RUTA_ID = (SELECT VIAJE_RUTA
										FROM THE_CVENGERS.VIAJE
										WHERE VIAJE_ID = ENCOMIENDA_VIAJE_ID)) + ((SELECT SERVICIO_PORCENTAJE/100
																				FROM THE_CVENGERS.SERVICIO
																				WHERE SERVICIO_ID = (SELECT AERONAVE_SERVICIO
																										FROM THE_CVENGERS.AERONAVE
																										WHERE AERONAVE_ID = (SELECT	VIAJE_AERONAVE
																																FROM THE_CVENGERS.VIAJE
																																WHERE VIAJE_ID = ENCOMIENDA_VIAJE_ID))) * (SELECT RUTA_PRECIO_BASE_POR_KILO *ENCOMIENDA_KG
																																										FROM THE_CVENGERS.RUTA
																																										WHERE RUTA_ID = (SELECT VIAJE_RUTA 
																																															FROM THE_CVENGERS.VIAJE
																																															WHERE VIAJE_ID = ENCOMIENDA_VIAJE_ID)))) /10) as int), (SELECT VIAJE_FECHA_LLEGADA	
																																																										FROM THE_CVENGERS.VIAJE
																																																										WHERE VIAJE_ID = ENCOMIENDA_VIAJE_ID)
																																							
FROM THE_CVENGERS.ENCOMIENDA
WHERE ENCOMIENDA_DEVOLUCION IS NULL
END
GO

CREATE PROCEDURE [THE_CVENGERS].getAll 
		@RECV  AS VARCHAR(30)
AS
BEGIN
	EXEC('SELECT * FROM ' + @RECV)
END
GO

EXECUTE [THE_CVENGERS].INIC_CLIENTE
EXECUTE [THE_CVENGERS].INIC_FABRICANTE
EXECUTE [THE_CVENGERS].INIC_CIUDAD
EXECUTE [THE_CVENGERS].INIC_COMPRA
EXECUTE [THE_CVENGERS].INIC_SERVICIO
EXECUTE [THE_CVENGERS].INIC_AERONAVE
EXECUTE [THE_CVENGERS].INIC_RUTA
EXECUTE [THE_CVENGERS].INIC_SERVICIOXRUTA
EXECUTE [THE_CVENGERS].INIC_VIAJE
EXECUTE [THE_CVENGERS].INIC_PASAJE
EXECUTE [THE_CVENGERS].INIC_ENCOMIENDA
EXECUTE [THE_CVENGERS].INIC_BUTACA
EXECUTE [THE_CVENGERS].INIC_BUTACAXVIAJE
EXECUTE [THE_CVENGERS].INIC_MILLA


go
create procedure THE_CVENGERS.setearFecha @P1 as datetime
as
begin
if(not exists(select * from THE_CVENGERS.FECHA))
begin
INSERT INTO THE_CVENGERS.FECHA (FECHA_RECIBIDA, FECHA_REFERENCIA)
VALUES (@P1,getdate())
end
end

go
create function THE_CVENGERS.fechaReal()
returns datetime
as
begin

declare @fechaRecibida datetime
set @fechaRecibida = (select F.FECHA_RECIBIDA from THE_CVENGERS.FECHA F )
declare @fechaReferencia datetime
set @fechaReferencia = (select F.FECHA_REFERENCIA from THE_CVENGERS.FECHA F )

declare @diffsegundo numeric(20,0)
set @diffsegundo = DATEDIFF(second, @fechaReferencia, getdate())

declare @fechaFinal datetime
set @fechaFinal = dateadd(second, @diffsegundo, @fechaRecibida)

return @fechaFinal
end

go
insert into [THE_CVENGERS].ROL (ROL_NOMBRE) values ('Administrador')
insert into [THE_CVENGERS].ROL (ROL_NOMBRE) values ('Cliente')

insert into [THE_CVENGERS].FUNCIONALIDAD (FUNC_NOMBRE, FUNC_DESCRIPCION) values ('ABM Ruta', 'Crear, modificar y eliminar Rutas'),
																				 ('ABM Aeronave', 'Crear, modificar y eliminar Aeronaves'),
																				 ('Generar viaje', 'Autorizacion para crear un viaje'),
																				 ('Registrar llegada a destino', 'Autorizacion para registrar la llegada de una aeronave'),
																				 ('Comprar pasaje - encomienda', 'Autorización para comprar pasajes y encomiendas'),
																				 ('Cancelación pasaje o encomienda', 'Autorizacion para cancelar pasajes o encomiendas'),
																				 ('ABM Rol', 'Crear, modificar y eliminar Roles'),
																				 ('Consultar Millas', 'Autorizacion para consultar millas'),
																				 ('Canje Millas', 'Autorizacion para canjear millas'),
																				 ('Listado Estadístico', 'Autorizacion para ver el listado estadístico'),
																				 ('ABM Ciudad', 'Crear, modificar y eliminar Ciudadades (próxima a implementarse)')
go
insert into [THE_CVENGERS].FUNCIONXROL (FXR_ROL_ID, FXR_FUNC_ID) values (1,1),
																		(1,2),
																		(1,3),
																		(1,4),
																		(1,5),
																		(1,6),
																		(1,7),
																		(1,8),
																		(1,9),
																		(1,10),
																		(1,11),
																		(2,5),
																		(2,8)

go
insert into THE_CVENGERS.USUARIO (USR_USERNAME) values ('Pepe'), ('Carlos'), ('Ricardo'), ('Guest')

go
insert into THE_CVENGERS.ROLXUSUARIO (ROLXUSUARIO_ROL, ROLXUSUARIO_USUARIO) values (1,1), (1,2), (1,3), (2,4)

go
insert into THE_CVENGERS.PRODUCTO (PRODUCTO_NOMBRE, PRODUCTO_STOCK, PRODUCTO_MILLAS_NECESARIAS) values ('Skate', 20, 1000),
																										('Auto 0 Km', 3, 10000),
																										('Cafetera', 25, 500),
																										('Notebook Core i7', 8, 4000),
																										('iPad 16Gb', 12, 3800) 

GO
INSERT INTO THE_CVENGERS.TIPO_TARJETA(TIPO_TARJETA_DETALLE) VALUES ('Visa'), ('MasterCard'), ('AMEX')

GO
INSERT INTO THE_CVENGERS.CUOTASXTARJETA(CUOTASXTARJETA_TIPO, CUOTASXTARJETA_CUOTAS) VALUES (1,1),
																							(1,3),
																							(1,6),
																							(1,12),
																							(2,1),
																							(2,3),
																							(2,6),
																							(3,1),
																							(3,3)

go
create procedure THE_CVENGERS.sumarFallido @USER AS NUMERIC(18,0)
AS
BEGIN
UPDATE THE_CVENGERS.USUARIO SET USR_FALLIDOS = (USR_FALLIDOS + 1)
WHERE USR_ID = @USER
END

go
create procedure THE_CVENGERS.deshabilitarUsuario @USER AS NUMERIC(18,0)
AS
BEGIN
UPDATE THE_CVENGERS.USUARIO SET USR_ESTADO = 0
WHERE USR_ID = @USER
END

go
create procedure THE_CVENGERS.resetearFallidos @USER AS NUMERIC(18,0)
AS
BEGIN
UPDATE THE_CVENGERS.USUARIO SET USR_FALLIDOS = 0
where USR_ID = @USER
END


go
CREATE PROCEDURE THE_CVENGERS.chequeoLogin @P1 AS nvarchar(100), @P2 AS varchar(100)
AS
BEGIN
DECLARE @USER numeric(18,0)
DECLARE @PASS VARCHAR(100)
SET @USER = (SELECT U.USR_ID FROM THE_CVENGERS.USUARIO U WHERE U.USR_USERNAME = @P1)
SET @PASS = (SELECT U.USR_PASS FROM THE_CVENGERS.USUARIO U WHERE U.USR_USERNAME = @P1)

IF (@USER IS NULL) 
BEGIN
RAISERROR('El usuario ingresado no existe',16,1)
RETURN 
END
IF ('Administrador' not in (SELECT R.ROL_NOMBRE FROM THE_CVENGERS.USUARIO U 
	JOIN THE_CVENGERS.ROLXUSUARIO RU ON U.USR_ID = RU.ROLXUSUARIO_USUARIO
	JOIN THE_CVENGERS.ROL R ON R.ROL_ID = RU.ROLXUSUARIO_ROL
	where u.USR_USERNAME = @P1))
BEGIN
RAISERROR('El usuario ingresado no posee el rol de Administrador',16,1)
RETURN
END
IF ((SELECT U.USR_ESTADO FROM THE_CVENGERS.USUARIO U WHERE U.USR_ID = @USER) = 0) 
BEGIN
RAISERROR('El usuario ingresado ha sido deshabilitado por realizar 3 intentos fallidos de logueo seguidos', 16,1)
RETURN
END
IF(@PASS <> hashbytes('SHA2_256',@P2)) 
BEGIN
EXEC THE_CVENGERS.sumarFallido @USER = @USER
IF((SELECT U.USR_FALLIDOS FROM THE_CVENGERS.USUARIO U WHERE U.USR_ID = @USER) = 3)
BEGIN
EXEC THE_CVENGERS.deshabilitarUsuario @USER = @USER
END
RAISERROR('La contraseña ingresada es incorrecta', 16,1)
RETURN
END
EXEC THE_CVENGERS.resetearFallidos @USER = @USER
RETURN
END
GO

create trigger THE_CVENGERS.deshabilitacionRol
on THE_CVENGERS.ROL
for UPDATE
as
BEGIN
DECLARE CURSOR_TRIG CURSOR
FOR SELECT ROL_ID, ROL_ESTADO FROM inserted

DECLARE @ESTADO BIT
DECLARE @IDROL NUMERIC(18,0)

open CURSOR_TRIG
FETCH FROM CURSOR_TRIG INTO @IDROL, @ESTADO 
WHILE @@FETCH_STATUS = 0
BEGIN

IF (@ESTADO = 0)
BEGIN
DELETE FROM THE_CVENGERS.ROLXUSUARIO
WHERE ROLXUSUARIO_ROL = @IDROL
END
FETCH NEXT FROM CURSOR_TRIG INTO @IDROL, @ESTADO 
END
CLOSE CURSOR_TRIG
DEALLOCATE CURSOR_TRIG
END
GO


CREATE PROCEDURE THE_CVENGERS.creacionRuta @P1 as numeric(18,0), @P2 as nvarchar(100), @P3 as nvarchar(100), @P4 as numeric(18,2), @P5 as numeric(18,2), @P6 as nvarchar(100), @P7 as nvarchar(100), @P8 as nvarchar(100)
as
begin
DECLARE @ORIGEN NUMERIC(18,0)
DECLARE @DESTINO NUMERIC(18,0)
DECLARE @SERV1 NUMERIC(18,0)
DECLARE @SERV2 NUMERIC(18,0)
DECLARE @SERV3 NUMERIC(18,0)

if(@P6 = 'NULL') SET @P6 = NULL
if(@P7 = 'NULL') SET @P7 = NULL
if(@P8 = 'NULL') SET @P8 = NULL


if(@P1 = 0)
BEGIN
RAISERROR('Por favor, ingrese un código de ruta válido.',16,1)
return
END 

if(@P6 IS NULL AND @P7 IS NULL AND @P8 IS NULL)
BEGIN
RAISERROR('La ruta debe tener por lo menos un tipo de servicio asignado.',16,1)
return
END 

SET @ORIGEN = (SELECT C.CIUDAD_ID FROM [THE_CVENGERS].CIUDAD C WHERE C.CIUDAD_NOMBRE like ('_' + @P2))
SET @DESTINO = (SELECT C.CIUDAD_ID FROM THE_CVENGERS.CIUDAD C WHERE C.CIUDAD_NOMBRE like ('_' + @P3))
SET @SERV1 = (SELECT S.SERVICIO_ID FROM THE_CVENGERS.SERVICIO S WHERE S.SERVICIO_NOMBRE = @P6)
SET @SERV2 = (SELECT S.SERVICIO_ID FROM THE_CVENGERS.SERVICIO S WHERE S.SERVICIO_NOMBRE = @P7)
SET @SERV3 = (SELECT S.SERVICIO_ID FROM THE_CVENGERS.SERVICIO S WHERE S.SERVICIO_NOMBRE = @P8)

if(exists(select R.RUTA_ID FROM THE_CVENGERS.RUTA R WHERE R.RUTA_ORIGEN = @ORIGEN AND R.RUTA_DESTINO = @DESTINO AND R.RUTA_ESTADO = 1))
BEGIN
RAISERROR('Ya existe una ruta con ese mismo origen y destino. Recuerde que puede agregar un servicio a una ruta mediante la opción de Modificación.',16,1)
return
end

insert into THE_CVENGERS.RUTA (RUTA_CODIGO, RUTA_ORIGEN, RUTA_DESTINO, RUTA_PRECIO_BASE_POR_KILO, RUTA_PRECIO_BASE_POR_PASAJE) 
values (@P1, @ORIGEN, @DESTINO, @P4, @P5)

declare @ruta numeric(18,0)

set @ruta = (select R.RUTA_ID FROM THE_CVENGERS.RUTA R WHERE R.RUTA_ORIGEN = @ORIGEN AND R.RUTA_DESTINO = @DESTINO)

if(@SERV1 is not null)
BEGIN
insert into THE_CVENGERS.SERVICIOXRUTA (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO)
values (@ruta, @SERV1)
END

if(@SERV2 is not null)
begin
insert into THE_CVENGERS.SERVICIOXRUTA (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO)
values (@ruta, @SERV2)
end

if(@SERV3 is not null)
begin
insert into THE_CVENGERS.SERVICIOXRUTA (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO)
values (@ruta, @SERV3)
end

return
end

go
CREATE PROCEDURE THE_CVENGERS.modificacionRuta @P0 as numeric(18,0), @P1 as numeric(18,0), @P4 as numeric(18,2), @P5 as numeric(18,2), @P6 as nvarchar(100), @P7 as nvarchar(100), @P8 as nvarchar(100)
as 
begin
DECLARE @SERV1 NUMERIC(18,0)
DECLARE @SERV2 NUMERIC(18,0)
DECLARE @SERV3 NUMERIC(18,0)

if(@P6 = 'NULL') SET @P6 = NULL
if(@P7 = 'NULL') SET @P7 = NULL
if(@P8 = 'NULL') SET @P8 = NULL

if(@P1 = 0)
BEGIN
RAISERROR('Por favor, ingrese un código de ruta válido.',16,1)
return
END 

if(@P6 IS NULL AND @P7 IS NULL AND @P8 IS NULL)
BEGIN
RAISERROR('La ruta debe tener por lo menos un tipo de servicio asignado.',16,1)
return
END 

SET @SERV1 = (SELECT S.SERVICIO_ID FROM THE_CVENGERS.SERVICIO S WHERE S.SERVICIO_NOMBRE = @P6)
SET @SERV2 = (SELECT S.SERVICIO_ID FROM THE_CVENGERS.SERVICIO S WHERE S.SERVICIO_NOMBRE = @P7)
SET @SERV3 = (SELECT S.SERVICIO_ID FROM THE_CVENGERS.SERVICIO S WHERE S.SERVICIO_NOMBRE = @P8)

IF(EXISTS(SELECT V.VIAJE_ID FROM THE_CVENGERS.VIAJE V WHERE V.VIAJE_RUTA = @P0 AND V.VIAJE_FECHA_LLEGADA <> NULL))
BEGIN
RAISERROR('No se puede modificar esta ruta debido a que existen viajes en curso o programados para la misma', 16,1)
return
END


update THE_CVENGERS.RUTA SET RUTA_CODIGO = @P1, RUTA_PRECIO_BASE_POR_KILO = @P4, RUTA_PRECIO_BASE_POR_PASAJE = @P5
WHERE RUTA_ID = @P0

if(@SERV1 is not null)
BEGIN
if(NOT EXISTS(SELECT S.SERVICIOXRUTA_RUTA FROM THE_CVENGERS.SERVICIOXRUTA S WHERE S.SERVICIOXRUTA_RUTA = @P0 AND S.SERVICIOXRUTA_SERVICIO = @SERV1))
BEGIN
insert into THE_CVENGERS.SERVICIOXRUTA (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO)
values (@P0, @SERV1)
END
END

if(@SERV2 is not null)
begin
if(NOT EXISTS(SELECT S.SERVICIOXRUTA_RUTA FROM THE_CVENGERS.SERVICIOXRUTA S WHERE S.SERVICIOXRUTA_RUTA = @P0 AND S.SERVICIOXRUTA_SERVICIO = @SERV2))
BEGIN
insert into THE_CVENGERS.SERVICIOXRUTA (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO)
values (@P0, @SERV2)
END
end

if(@SERV3 is not null)
begin
if(NOT EXISTS(SELECT S.SERVICIOXRUTA_RUTA FROM THE_CVENGERS.SERVICIOXRUTA S WHERE S.SERVICIOXRUTA_RUTA = @P0 AND S.SERVICIOXRUTA_SERVICIO = @SERV3))
BEGIN
insert into THE_CVENGERS.SERVICIOXRUTA (SERVICIOXRUTA_RUTA, SERVICIOXRUTA_SERVICIO)
values (@P0, @SERV3)
END
end

DECLARE @V1 NUMERIC(2,0)
SET @V1 = (CASE WHEN @SERV2 IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN @SERV1 IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN @SERV3 IS NOT NULL THEN 1 ELSE 0 END)
IF((SELECT COUNT(*) FROM THE_CVENGERS.SERVICIOXRUTA S WHERE S.SERVICIOXRUTA_RUTA = @P0) <> @V1)
BEGIN

IF(@SERV1 IS NOT NULL AND @SERV2 IS NULL AND @SERV3 IS NULL)
BEGIN
DELETE FROM THE_CVENGERS.SERVICIOXRUTA
WHERE SERVICIOXRUTA_RUTA = @P0 AND SERVICIOXRUTA_SERVICIO <> @SERV1
END

IF(@SERV1 IS NULL AND @SERV2 IS NOT NULL AND @SERV3 IS NULL)
BEGIN
DELETE FROM THE_CVENGERS.SERVICIOXRUTA
WHERE SERVICIOXRUTA_RUTA = @P0 AND SERVICIOXRUTA_SERVICIO <> @SERV2
END

IF(@SERV1 IS NULL AND @SERV2 IS NULL AND @SERV3 IS NOT NULL)
BEGIN
DELETE FROM THE_CVENGERS.SERVICIOXRUTA
WHERE SERVICIOXRUTA_RUTA = @P0 AND SERVICIOXRUTA_SERVICIO <> @SERV3
END

IF(@SERV1 IS NOT NULL AND @SERV2 IS NOT NULL AND @SERV3 IS NULL)
BEGIN
DELETE FROM THE_CVENGERS.SERVICIOXRUTA
WHERE SERVICIOXRUTA_RUTA = @P0 AND SERVICIOXRUTA_SERVICIO <> @SERV1 AND SERVICIOXRUTA_SERVICIO <> @SERV2
END

IF(@SERV1 IS NOT NULL AND @SERV2 IS NULL AND @SERV3 IS NOT NULL)
BEGIN
DELETE FROM THE_CVENGERS.SERVICIOXRUTA
WHERE SERVICIOXRUTA_RUTA = @P0 AND SERVICIOXRUTA_SERVICIO <> @SERV1 AND SERVICIOXRUTA_SERVICIO <> @SERV3
END

IF(@SERV1 IS NULL AND @SERV2 IS NOT NULL AND @SERV3 IS NOT NULL)
BEGIN
DELETE FROM THE_CVENGERS.SERVICIOXRUTA
WHERE SERVICIOXRUTA_RUTA = @P0 AND SERVICIOXRUTA_SERVICIO <> @SERV2 AND SERVICIOXRUTA_SERVICIO <> @SERV3
END

END
return
end

go
create view THE_CVENGERS.RutasDisponibles
as
select R.RUTA_ID 'Id', R.RUTA_CODIGO 'Código de Rutas', (select C.CIUDAD_NOMBRE 
										FROM THE_CVENGERS.CIUDAD C 
										WHERE C.CIUDAD_ID = R.RUTA_ORIGEN) 'Origen', (select C.CIUDAD_NOMBRE 
																						FROM THE_CVENGERS.CIUDAD C 
																						WHERE C.CIUDAD_ID = R.RUTA_DESTINO) 'Destino', R.RUTA_PRECIO_BASE_POR_KILO 'Precio Base por Kilo', R.RUTA_PRECIO_BASE_POR_PASAJE 'Precio Base por Pasaje', isnull((SELECT 'Sí' from THE_CVENGERS.SERVICIOXRUTA WHERE SERVICIOXRUTA_RUTA = R.RUTA_ID AND SERVICIOXRUTA_SERVICIO = 1), 'No') 'Primera Clase', isnull((SELECT 'Sí' from THE_CVENGERS.SERVICIOXRUTA WHERE SERVICIOXRUTA_RUTA = R.RUTA_ID AND SERVICIOXRUTA_SERVICIO = 2), 'No') 'Ejecutivo', isnull((SELECT 'Sí' from THE_CVENGERS.SERVICIOXRUTA WHERE SERVICIOXRUTA_RUTA = R.RUTA_ID AND SERVICIOXRUTA_SERVICIO = 3), 'No') 'Turista'
from THE_CVENGERS.RUTA R
where R.RUTA_ESTADO = 1

go
create procedure THE_CVENGERS.ingresoAeronave @matri as nvarchar(100), @model as nvarchar(100), @fabricante as numeric(18,0),
												@serv as numeric(18,0), @butacas as numeric(18,0), @espacio as numeric(18,2),
												@pisos as numeric(3,0) 
as
begin

if(exists(select AERONAVE_ID FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_MATRICULA_AVION = @matri))
begin
raiserror('Ya existe un avión con ese número de matrícula.',16,1)
return
end

insert into THE_CVENGERS.AERONAVE (AERONAVE_MATRICULA_AVION,AERONAVE_MODELO_AVION,AERONAVE_FABRICANTE_AVION,
									AERONAVE_SERVICIO, AERONAVE_CANTIDAD_BUTACAS, AERONAVE_ESPACIO_ENCOMIENDAS, AERONAVE_FECHA_DE_ALTA) values
									(@matri, @model, @fabricante, @serv, @butacas, @espacio, THE_CVENGERS.fechaReal())

declare @aeronave numeric(18,0)
set @aeronave = (select AERONAVE_ID  from THE_CVENGERS.AERONAVE where AERONAVE_MATRICULA_AVION = @matri)

declare @numbut numeric(10,0)
set @numbut = 0

declare @numpiso numeric(10,0)
set @numpiso = 1

declare @butacasXpiso numeric(10,0)
set @butacasXpiso = @butacas/@pisos

declare @tipobut numeric(10,0)
set @tipobut = 0

while @numbut < @butacas
begin

if(@numbut = @butacasXpiso) set @numpiso = @numpiso + 1

insert into THE_CVENGERS.BUTACA (BUTACA_AERONAVE,BUTACA_NRO, BUTACA_PISO, BUTACA_TIPO)
values (@aeronave, @numbut, @numpiso, (case when @tipobut = 0 then 'Ventanilla' else 'Pasillo' end))

if(@tipobut = 1) set @tipobut = 0 else set @tipobut = 1
 
set @numbut = @numbut +1
end
end

go
create function THE_CVENGERS.viajeARegistrar (@matricula as nvarchar(100), @origen as nvarchar(100), @destino as nvarchar(100))
returns numeric
as
begin

declare @viajeBuscado numeric(18,0)
set @viajeBuscado = (select V.VIAJE_ID 
				from THE_CVENGERS.VIAJE V 
				WHERE V.VIAJE_RUTA = (SELECT R.RUTA_ID
										FROM THE_CVENGERS.RUTA R
										WHERE R.RUTA_ORIGEN = (SELECT C.CIUDAD_ID 
																from THE_CVENGERS.CIUDAD C
																where c.CIUDAD_NOMBRE like ('_'+ @origen))
										and r.RUTA_DESTINO = (SELECT C.CIUDAD_ID 
																from THE_CVENGERS.CIUDAD C
																where c.CIUDAD_NOMBRE like ('_'+ @destino))) and V.VIAJE_AERONAVE = (select AERONAVE_ID from THE_CVENGERS.AERONAVE where AERONAVE_MATRICULA_AVION = @matricula) and V.VIAJE_FECHA_SALIDA < THE_CVENGERS.fechaReal() and v.VIAJE_FECHA_LLEGADA is NULL and V.VIAJE_ESTADO = 1)

if(@viajeBuscado is NULL)
begin
return cast('No hay ningún viaje en proceso de esa Aeronave sobre esa ruta.' as int);
end
return @viajeBuscado
end

go
create procedure THE_CVENGERS.asignarMillasViaje @viaje as numeric(18,0)
as
begin


INSERT INTO THE_CVENGERS.MILLA (MILLA_CLIENTE, MILLA_GANADA, MILLA_FECHA_ACREDITACION)
SELECT PASAJE_CLI_ID, cast((((SELECT RUTA_PRECIO_BASE_POR_PASAJE
						FROM THE_CVENGERS.RUTA
						WHERE RUTA_ID = (SELECT VIAJE_RUTA
										FROM THE_CVENGERS.VIAJE
										WHERE VIAJE_ID = @viaje)) + ((SELECT SERVICIO_PORCENTAJE/100
																				FROM THE_CVENGERS.SERVICIO
																				WHERE SERVICIO_ID = (SELECT AERONAVE_SERVICIO
																										FROM THE_CVENGERS.AERONAVE
																										WHERE AERONAVE_ID = (SELECT	VIAJE_AERONAVE
																																FROM THE_CVENGERS.VIAJE
																																WHERE VIAJE_ID = @viaje))) * (SELECT RUTA_PRECIO_BASE_POR_PASAJE
																																										FROM THE_CVENGERS.RUTA
																																										WHERE RUTA_ID = (SELECT VIAJE_RUTA 
																																															FROM THE_CVENGERS.VIAJE
																																															WHERE VIAJE_ID = @viaje)))) /10) as int), (select VIAJE_FECHA_LLEGADA 
																																																										from THE_CVENGERS.VIAJE
																																																										where VIAJE_ID = @viaje)
FROM THE_CVENGERS.PASAJE
WHERE PASAJE_VIAJE_ID = @viaje AND PASAJE_DEVOLUCION IS NULL


INSERT INTO THE_CVENGERS.MILLA (MILLA_CLIENTE, MILLA_GANADA, MILLA_FECHA_ACREDITACION)
SELECT ENCOMIENDA_CLI_ID, cast((((SELECT RUTA_PRECIO_BASE_POR_KILO* ENCOMIENDA_KG
									FROM THE_CVENGERS.RUTA
									WHERE RUTA_ID = (SELECT VIAJE_RUTA
													FROM THE_CVENGERS.VIAJE
													WHERE VIAJE_ID = @viaje)) + ((SELECT SERVICIO_PORCENTAJE/100
																							FROM THE_CVENGERS.SERVICIO
																							WHERE SERVICIO_ID = (SELECT AERONAVE_SERVICIO
																													FROM THE_CVENGERS.AERONAVE
																													WHERE AERONAVE_ID = (SELECT	VIAJE_AERONAVE
																																			FROM THE_CVENGERS.VIAJE
																																			WHERE VIAJE_ID = @viaje))) * (SELECT RUTA_PRECIO_BASE_POR_KILO * ENCOMIENDA_KG
																																													FROM THE_CVENGERS.RUTA
																																													WHERE RUTA_ID = (SELECT VIAJE_RUTA 
																																																		FROM THE_CVENGERS.VIAJE
																																																		WHERE VIAJE_ID = @viaje)))) /10) as int), (select VIAJE_FECHA_LLEGADA 
																																																													from THE_CVENGERS.VIAJE
																																																													where VIAJE_ID = @viaje)
FROM THE_CVENGERS.ENCOMIENDA
WHERE ENCOMIENDA_VIAJE_ID = @viaje AND ENCOMIENDA_DEVOLUCION IS NULL


end



go
create procedure THE_CVENGERS.registrarLLegada @viaje as numeric(18,0), @fecha as datetime
as
begin

update THE_CVENGERS.VIAJE set VIAJE_FECHA_LLEGADA = @fecha
where VIAJE_ID = @viaje

EXEC THE_CVENGERS.asignarMillasViaje @viaje = @viaje

end

go
create procedure THE_CVENGERS.generarViaje @aeronave as numeric(18,0), @ruta as numeric(18,0), @salida as datetime, @llegadaest as datetime
as
begin

if(exists(select viaje_id from THE_CVENGERS.VIAJE where VIAJE_AERONAVE = @aeronave and datediff(day,VIAJE_FECHA_SALIDA, @salida) <= 1 and VIAJE_FECHA_LLEGADA is null))
begin
raiserror('Esa aeronave ya tiene un viaje asignado en ese lapso de tiempo', 16, 1)
return
end

insert into THE_CVENGERS.VIAJE (VIAJE_AERONAVE,VIAJE_RUTA,VIAJE_FECHA_SALIDA, VIAJE_FECHA_LLEGADA_ESTIMADA)
VALUES (@aeronave, @ruta, @salida, @llegadaest)

declare @viaje numeric(18,0)
set @viaje = (select VIAJE_ID from THE_CVENGERS.VIAJE where VIAJE_AERONAVE = @aeronave and VIAJE_RUTA = @ruta and VIAJE_FECHA_SALIDA = @salida and VIAJE_FECHA_LLEGADA_ESTIMADA = @llegadaest) 

declare @cantButacas numeric(18,0)
set @cantButacas = (select AERONAVE_CANTIDAD_BUTACAS from THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @aeronave)

declare @numButaca numeric(3,0)
set @numButaca = 0

while(@numButaca < @cantButacas)
begin

insert into THE_CVENGERS.BUTACAXVIAJE (BUTACAXVIAJE_VIAJE_ID, BUTACAXVIAJE_BUTACA_ID)
VALUES (@viaje, (SELECT BUTACA_ID FROM THE_CVENGERS.BUTACA WHERE BUTACA_AERONAVE = @aeronave AND BUTACA_NRO = @numButaca))

set @numButaca = @numButaca + 1

end

end

go
create view THE_CVENGERS.viajesCompra
as
select V.VIAJE_ID 'Id', (select CIUDAD_NOMBRE
							from THE_CVENGERS.CIUDAD
							where CIUDAD_ID = (select RUTA_ORIGEN
												from THE_CVENGERS.RUTA
												where RUTA_ID = V.VIAJE_RUTA)) 'Origen', (select CIUDAD_NOMBRE
																							from THE_CVENGERS.CIUDAD
																							where CIUDAD_ID = (select RUTA_DESTINO
																												from THE_CVENGERS.RUTA
																												where RUTA_ID = V.VIAJE_RUTA)) 'Destino', V.VIAJE_FECHA_SALIDA 'Fecha de salida', (select SERVICIO_NOMBRE
																																																	from THE_CVENGERS.SERVICIO
																																																	WHERE SERVICIO_ID = (select AERONAVE_SERVICIO
																																																							from THE_CVENGERS.AERONAVE
																																																							where AERONAVE_ID = VIAJE_AERONAVE)) 'Tipo de servicio', (select count(*)
																																																																						from THE_CVENGERS.BUTACAXVIAJE
																																																																						where BUTACAXVIAJE_VIAJE_ID = VIAJE_ID
																																																																						and BUTACAXVIAJE_PASAJE_ID is null) 'Butacas disponibles', ((select AERONAVE_ESPACIO_ENCOMIENDAS
																																																																																							FROM THE_CVENGERS.AERONAVE
																																																																																							WHERE AERONAVE_ID = VIAJE_AERONAVE)-(select isnull(sum(ENCOMIENDA_KG),0)	
																																																																																																	from THE_CVENGERS.ENCOMIENDA
																																																																																																	where ENCOMIENDA_VIAJE_ID = VIAJE_ID AND ENCOMIENDA_DEVOLUCION IS NULL)) 'Kg disponibles'
from THE_CVENGERS.VIAJE V
WHERE V.VIAJE_FECHA_LLEGADA IS NULL AND V.VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal() AND VIAJE_ESTADO = 1

go
create function THE_CVENGERS.destinosConMasPasajesComprados(@anio as int, @semestre as int)
returns table
as

return (select top 5 CIUDAD_NOMBRE 'Destino', (SELECT COUNT(*) 
									FROM THE_CVENGERS.PASAJE
									WHERE PASAJE_VIAJE_ID IN (SELECT VIAJE_ID
																FROM THE_CVENGERS.VIAJE
																WHERE VIAJE_RUTA IN (SELECT RUTA_ID
																					FROM THE_CVENGERS.RUTA
																					WHERE RUTA_DESTINO = CIUDAD_ID)) AND PASAJE_COMPRA IN (select COMPRA_ID
																																			FROM THE_CVENGERS.COMPRA
																																			WHERE YEAR(COMPRA_FECHA) = @anio AND month(COMPRA_FECHA) between (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end))AND PASAJE_DEVOLUCION IS NULL) 'Pasajes vendidos'
										
from THE_CVENGERS.CIUDAD
where CIUDAD_ID IN (SELECT RUTA_DESTINO FROM THE_CVENGERS.RUTA WHERE RUTA_ID IN (SELECT VIAJE_RUTA FROM THE_CVENGERS.VIAJE))
ORDER BY "Pasajes vendidos" desc)

go
create function THE_CVENGERS.destinosConAeronavesMasVacias(@anio as int, @semestre as int)
returns table
as

return (select top 5 CIUDAD_NOMBRE 'Destino', (SELECT COUNT(*) 
												from THE_CVENGERS.BUTACAXVIAJE
												WHERE BUTACAXVIAJE_VIAJE_ID IN (SELECT VIAJE_ID	
																				FROM VIAJE
																				WHERE VIAJE_RUTA IN (SELECT RUTA_ID
																										FROM THE_CVENGERS.RUTA
																										WHERE RUTA_DESTINO = CIUDAD_ID)
																				AND VIAJE_FECHA_LLEGADA IS NOT NULL
																				AND YEAR(VIAJE_FECHA_LLEGADA) = @anio
																				AND month(VIAJE_FECHA_LLEGADA) between (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end) AND VIAJE_ESTADO = 1)) 'Total pasajes disponibles',  (SELECT COUNT(*) 
																																																														from THE_CVENGERS.BUTACAXVIAJE
																																																														WHERE BUTACAXVIAJE_VIAJE_ID IN (SELECT VIAJE_ID	
																																																																						FROM VIAJE
																																																																						WHERE VIAJE_RUTA IN (SELECT RUTA_ID
																																																																												FROM THE_CVENGERS.RUTA
																																																																												WHERE RUTA_DESTINO = CIUDAD_ID)
																																																																						AND VIAJE_FECHA_LLEGADA IS NOT NULL
																																																																						AND YEAR(VIAJE_FECHA_LLEGADA) = @anio
																																																																						AND month(VIAJE_FECHA_LLEGADA) between (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end) AND VIAJE_ESTADO = 1)
																																																																						and BUTACAXVIAJE_PASAJE_ID IS NOT NULL) 'Total pasajes comprados', 100 - (((SELECT COUNT(*) 
																																																																																								from THE_CVENGERS.BUTACAXVIAJE
																																																																																								WHERE BUTACAXVIAJE_VIAJE_ID IN (SELECT VIAJE_ID	
																																																																																																FROM VIAJE
																																																																																																WHERE VIAJE_RUTA IN (SELECT RUTA_ID
																																																																																																						FROM THE_CVENGERS.RUTA
																																																																																																						WHERE RUTA_DESTINO = CIUDAD_ID)
																																																																																																AND VIAJE_FECHA_LLEGADA IS NOT NULL
																																																																																																AND YEAR(VIAJE_FECHA_LLEGADA) = @anio
																																																																																																AND month(VIAJE_FECHA_LLEGADA) between (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end) AND VIAJE_ESTADO = 1)
																																																																																																and BUTACAXVIAJE_PASAJE_ID IS NOT NULL) / (SELECT COUNT(*) 
																																																																																																																	from THE_CVENGERS.BUTACAXVIAJE
																																																																																																																	WHERE BUTACAXVIAJE_VIAJE_ID IN (SELECT VIAJE_ID	
																																																																																																																									FROM VIAJE
																																																																																																																									WHERE VIAJE_RUTA IN (SELECT RUTA_ID
																																																																																																																															FROM THE_CVENGERS.RUTA
																																																																																																																															WHERE RUTA_DESTINO = CIUDAD_ID)
																																																																																																																									AND VIAJE_FECHA_LLEGADA IS NOT NULL
																																																																																																																									AND YEAR(VIAJE_FECHA_LLEGADA) = @anio
																																																																																																																									AND month(VIAJE_FECHA_LLEGADA) between (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end) AND VIAJE_ESTADO = 1)))*100) 'Porcentaje de desocupación'
from THE_CVENGERS.CIUDAD
where CIUDAD_ID IN (SELECT RUTA_DESTINO FROM THE_CVENGERS.RUTA WHERE RUTA_ID IN (SELECT VIAJE_RUTA FROM THE_CVENGERS.VIAJE))
ORDER BY "Porcentaje de desocupación" DESC, "Total pasajes disponibles" DESC, "Total pasajes comprados" DESC)

go
create function THE_CVENGERS.clientesConMasPuntosAcumulados(@anio as int, @semestre as int)
returns table
as

return(select top 5 CLIENTE_APELLIDO + ' ' + CLIENTE_NOMBRE 'Cliente', (select sum(MILLA_GANADA)
																		FROM THE_CVENGERS.MILLA
																		WHERE MILLA_CLIENTE = CLIENTE_ID
																		AND YEAR(MILLA_FECHA_ACREDITACION) <= @anio
																		AND month(MILLA_FECHA_ACREDITACION) IN ((case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 1  else 1 end), (case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 2  else 2 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 3 else 3 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 4 else 4 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 5  else 5 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 6 else 6 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 0 ELSE 7 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 0  else 8 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 0  else 9 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 0 else 10 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 0 else 11 end),(case when YEAR(MILLA_FECHA_ACREDITACION) = @anio and @semestre = 1 then 0 else 12 end))) 'Millas totales acumuladas'
		from THE_CVENGERS.CLIENTE
		order by "Millas totales acumuladas" DESC)

go
create function THE_CVENGERS.destinosConMasPasajesCancelados(@anio as int, @semestre as int)
returns table
as
return(select top 5  CIUDAD_NOMBRE 'Destino', (SELECT COUNT(*) 
												FROM THE_CVENGERS.PASAJE
												WHERE PASAJE_VIAJE_ID IN (SELECT VIAJE_ID 
																			FROM THE_CVENGERS.VIAJE
																			WHERE VIAJE_RUTA IN (SELECT RUTA_ID	
																									FROM THE_CVENGERS.RUTA
																									WHERE RUTA_DESTINO = CIUDAD_ID))
												AND PASAJE_DEVOLUCION IS NOT NULL
												AND PASAJE_DEVOLUCION IN (SELECT DEVOLUCION_ID FROM THE_CVENGERS.DEVOLUCION
																			WHERE YEAR(DEVOLUCION_FECHA) = @anio AND MONTH(DEVOLUCION_FECHA) between (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end)) ) 'Pasajes cancelados'

		from THE_CVENGERS.CIUDAD
		where CIUDAD_ID IN (SELECT RUTA_DESTINO FROM THE_CVENGERS.RUTA WHERE RUTA_ID IN (SELECT VIAJE_RUTA FROM THE_CVENGERS.VIAJE))
		order by "Pasajes cancelados" DESC)

go
create function THE_CVENGERS.consultarMillas(@cli as numeric(18,0))
returns int
as
begin
return (select isnull(sum(MILLA_GANADA - MILLA_GASTADA), 0)
		FROM THE_CVENGERS.MILLA
		WHERE MILLA_CLIENTE = @cli
		AND DATEDIFF(second,MILLA_FECHA_ACREDITACION, THE_CVENGERS.fechaReal()) <= 31536000)
end

go
create function THE_CVENGERS.calcularPrecioPasaje(@viaje as numeric(18,0))
returns numeric(18,2)
as
begin
return ((SELECT RUTA_PRECIO_BASE_POR_PASAJE 
						FROM THE_CVENGERS.RUTA
						WHERE RUTA_ID = (SELECT VIAJE_RUTA
										FROM THE_CVENGERS.VIAJE
										WHERE VIAJE_ID = @viaje)) + ((SELECT SERVICIO_PORCENTAJE/100
																				FROM THE_CVENGERS.SERVICIO
																				WHERE SERVICIO_ID = (SELECT AERONAVE_SERVICIO
																										FROM THE_CVENGERS.AERONAVE
																										WHERE AERONAVE_ID = (SELECT	VIAJE_AERONAVE
																																FROM THE_CVENGERS.VIAJE
																																WHERE VIAJE_ID = @viaje))) * (SELECT RUTA_PRECIO_BASE_POR_PASAJE 
																																										FROM THE_CVENGERS.RUTA
																																										WHERE RUTA_ID = (SELECT VIAJE_RUTA 
																																															FROM THE_CVENGERS.VIAJE
																																															WHERE VIAJE_ID = @viaje))))
end
		
go
create function THE_CVENGERS.calcularPrecioEncomienda(@viaje as numeric(18,0), @kg as numeric(18,0))
returns numeric(18,2)
as
begin
return ((SELECT RUTA_PRECIO_BASE_POR_KILO * @kg
						FROM THE_CVENGERS.RUTA
						WHERE RUTA_ID = (SELECT VIAJE_RUTA
										FROM THE_CVENGERS.VIAJE
										WHERE VIAJE_ID = @viaje)) + ((SELECT SERVICIO_PORCENTAJE/100
																				FROM THE_CVENGERS.SERVICIO
																				WHERE SERVICIO_ID = (SELECT AERONAVE_SERVICIO
																										FROM THE_CVENGERS.AERONAVE
																										WHERE AERONAVE_ID = (SELECT	VIAJE_AERONAVE
																																FROM THE_CVENGERS.VIAJE
																																WHERE VIAJE_ID = @viaje))) * (SELECT RUTA_PRECIO_BASE_POR_KILO *@kg
																																										FROM THE_CVENGERS.RUTA
																																										WHERE RUTA_ID = (SELECT VIAJE_RUTA 
																																															FROM THE_CVENGERS.VIAJE
																																															WHERE VIAJE_ID = @viaje))))
end

go
create procedure THE_CVENGERS.realizarCanje @cli as numeric(18,0), @prod as numeric(18,0), @cant as NUMERIC(18,0)
as
begin

declare @millasACobrar int
set @millasACobrar = (SELECT PRODUCTO_MILLAS_NECESARIAS * @cant
						FROM THE_CVENGERS.PRODUCTO
						WHERE PRODUCTO_ID = @prod)

declare @IdMilla numeric(18,0)
declare @ganada numeric(18,0)
declare @gastada numeric(18,0)

declare restarMillas cursor
for SELECT MILLA_ID, MILLA_GANADA, MILLA_GASTADA FROM THE_CVENGERS.MILLA WHERE MILLA_CLIENTE = @cli AND DATEDIFF(SECOND, MILLA_FECHA_ACREDITACION, THE_CVENGERS.fechaReal()) <= 31536000 ORDER BY MILLA_FECHA_ACREDITACION


OPEN restarMillas
FETCH FROM restarMillas INTO @IdMilla, @ganada, @gastada
WHILE @millasACobrar <> 0
BEGIN
if(@gastada = 0)
begin
if (@ganada <= @millasACobrar)
begin

set @millasACobrar = @millasACobrar - @ganada

update THE_CVENGERS.MILLA SET MILLA_GASTADA = MILLA_GANADA
WHERE MILLA_ID = @IdMilla

end
else
begin

update THE_CVENGERS.MILLA SET MILLA_GASTADA = @millasACobrar
WHERE MILLA_ID = @IdMilla

set @millasACobrar = 0
end
end

if(@gastada <> 0 and @gastada < @ganada)
begin

if((@ganada - @gastada) < @millasACobrar)
begin

set @millasACobrar = @millasACobrar - (@ganada - @gastada)

update THE_CVENGERS.MILLA SET MILLA_GASTADA = MILLA_GANADA
WHERE MILLA_ID = @IdMilla

end

if((@ganada - @gastada) > @millasACobrar)
begin

update THE_CVENGERS.MILLA SET MILLA_GASTADA = MILLA_GASTADA + @millasACobrar
WHERE MILLA_ID = @IdMilla

 set @millasACobrar = 0

end

end

FETCH NEXT FROM restarMillas INTO @IdMilla, @ganada, @gastada
END
CLOSE restarMillas
DEALLOCATE restarMillas

UPDATE THE_CVENGERS.PRODUCTO SET PRODUCTO_STOCK = PRODUCTO_STOCK - @cant
WHERE PRODUCTO_ID = @prod

INSERT INTO THE_CVENGERS.CANJE (CANJE_CLIENTE, CANJE_PROD, CANJE_FECHA, CANJE_CANTIDAD)
VALUES (@cli, @prod, THE_CVENGERS.fechaReal(), @cant)

END

go
create function THE_CVENGERS.listadoMillas(@cli as numeric(18,0))
returns table
as
return(SELECT MILLA_FECHA_ACREDITACION 'Fecha transacción', MILLA_GANADA 'Millas' FROM THE_CVENGERS.MILLA WHERE MILLA_CLIENTE = @cli
		UNION all
		SELECT CANJE_FECHA 'Fecha transacción', (SELECT '-' + cast((PRODUCTO_MILLAS_NECESARIAS*CANJE_CANTIDAD) AS char) 'Millas' FROM THE_CVENGERS.PRODUCTO WHERE PRODUCTO_ID = CANJE_PROD)FROM THE_CVENGERS.CANJE where CANJE_CLIENTE = @cli
		)

go
create function THE_CVENGERS.listadoCanjes(@cli as numeric(18,0))
returns table
as
return(select CANJE_FECHA 'Fecha canje', PRODUCTO_NOMBRE 'Producto', CANJE_CANTIDAD 'Cantidad', (CANJE_CANTIDAD*PRODUCTO_MILLAS_NECESARIAS) 'Millas gastadas' from THE_CVENGERS.CANJE join THE_CVENGERS.PRODUCTO ON CANJE_PROD = PRODUCTO_ID where CANJE_CLIENTE = @cli)

go
create function THE_CVENGERS.comprasCliente(@cli as numeric(18,0))
returns table
as
return(SELECT COMPRA_FECHA 'Fecha compra', COMPRA_ID 'Número de compra' FROM THE_CVENGERS.COMPRA WHERE COMPRA_CLIENTE = @cli AND (0 <> (SELECT COUNT(*)
																										FROM THE_CVENGERS.PASAJE
																										WHERE PASAJE_COMPRA = COMPRA_ID
																										AND PASAJE_DEVOLUCION IS NULL) OR 0 <> (SELECT COUNT(*)
																																				FROM THE_CVENGERS.ENCOMIENDA
																																				WHERE ENCOMIENDA_COMPRA = COMPRA_ID
																																				AND ENCOMIENDA_DEVOLUCION IS NULL)) AND ((COMPRA_ID IN (SELECT PASAJE_COMPRA FROM THE_CVENGERS.PASAJE
																																																		WHERE PASAJE_VIAJE_ID IN (SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
																																																									WHERE VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal()))) or (COMPRA_ID IN (SELECT ENCOMIENDA_COMPRA FROM THE_CVENGERS.ENCOMIENDA
																																																																												WHERE ENCOMIENDA_VIAJE_ID IN (SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
																																																																																			WHERE VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal())))))


go
create function THE_CVENGERS.itemsDeCompra(@compra as numeric(18,0))
returns table
as
return(SELECT PASAJE_ID 'Número de item', 'Pasaje' 'Tipo', THE_CVENGERS.calcularPrecioPasaje(PASAJE_VIAJE_ID) 'Precio' FROM THE_CVENGERS.PASAJE WHERE PASAJE_DEVOLUCION IS NULL AND PASAJE_COMPRA = @compra AND PASAJE_VIAJE_ID IN (SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
																																																									WHERE VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal())
       UNION ALL
	   SELECT ENCOMIENDA_ID 'Número de item', 'Encomienda' 'Tipo', THE_CVENGERS.calcularPrecioEncomienda(ENCOMIENDA_VIAJE_ID, ENCOMIENDA_KG) 'Precio' FROM THE_CVENGERS.ENCOMIENDA WHERE ENCOMIENDA_DEVOLUCION IS NULL AND ENCOMIENDA_COMPRA = @compra AND ENCOMIENDA_VIAJE_ID IN (SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
																																																																					WHERE VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal())) 


go
create procedure THE_CVENGERS.crearDevolucion(@compra as numeric(18,0), @descripcion as nvarchar(100))
as
begin
insert into THE_CVENGERS.DEVOLUCION (DEVOLUCION_FECHA, DEVOLUCION_NUM_COMPRA, DEVOLUCION_DESCRIPCION)
values (THE_CVENGERS.fechaReal(), @compra, @descripcion)
end


go
create procedure THE_CVENGERS.devolverItem(@item as numeric(18,0), @tipoItem as nvarchar(25))
as
begin
if(@tipoItem = 'Encomienda')
begin
update THE_CVENGERS.ENCOMIENDA SET ENCOMIENDA_DEVOLUCION = (SELECT TOP 1 DEVOLUCION_ID FROM THE_CVENGERS.DEVOLUCION WHERE DEVOLUCION_NUM_COMPRA = ENCOMIENDA_COMPRA ORDER BY DEVOLUCION_ID DESC) 
WHERE ENCOMIENDA_ID = @item
end
if(@tipoItem = 'Pasaje')
BEGIN
update THE_CVENGERS.PASAJE SET PASAJE_DEVOLUCION = (SELECT TOP 1 DEVOLUCION_ID FROM THE_CVENGERS.DEVOLUCION WHERE DEVOLUCION_NUM_COMPRA = PASAJE_COMPRA ORDER BY DEVOLUCION_ID DESC) 
WHERE PASAJE_ID = @item

UPDATE THE_CVENGERS.BUTACAXVIAJE SET BUTACAXVIAJE_PASAJE_ID = NULL
WHERE BUTACAXVIAJE_PASAJE_ID = @item

END
END

go
create procedure THE_CVENGERS.ingresarOModificarCliente(@id as numeric(18,0),@nombre as nvarchar(100), @apellido as nvarchar(100),
@dni as numeric(18,0), @dir as nvarchar(100), @telefono as numeric(18,0), @mail as nvarchar(100), @fechanac as datetime)
as
begin

if(@id = 0)
begin
insert into THE_CVENGERS.CLIENTE (CLIENTE_APELLIDO,CLIENTE_NOMBRE,CLIENTE_DNI, CLIENTE_DIR, CLIENTE_FECHA_NAC, CLIENTE_MAIL, CLIENTE_TELEFONO)
VALUES(@apellido,@nombre,@dni,@dir,@fechanac,@mail,@telefono)
end
else
begin
update THE_CVENGERS.CLIENTE SET CLIENTE_APELLIDO = @apellido, CLIENTE_NOMBRE = @nombre, CLIENTE_DNI = @dni,
CLIENTE_DIR = @dir, CLIENTE_FECHA_NAC = @fechanac, CLIENTE_MAIL = @mail, CLIENTE_TELEFONO = @telefono
WHERE CLIENTE_ID = @id
END
END

go
create function THE_CVENGERS.tipoTarjetaCompra(@compra as numeric(18,0))
returns nvarchar
as
begin
return (select TIPO_TARJETA_DETALLE FROM THE_CVENGERS.TIPO_TARJETA
		WHERE TIPO_TARJETA_ID = (SELECT TARJETA_TIPO FROM THE_CVENGERS.TARJETACREDITO
									WHERE TARJETA_ID = (SELECT COMPRA_TARJETA FROM THE_CVENGERS.COMPRA
														WHERE COMPRA_ID = @compra)))
end

go
create function THE_CVENGERS.numeroTarjetaCompra(@compra as numeric(18,0))
returns nvarchar
as
begin
return (SELECT TARJETA_NRO FROM THE_CVENGERS.TARJETACREDITO
									WHERE TARJETA_ID = (SELECT COMPRA_TARJETA FROM THE_CVENGERS.COMPRA
														WHERE COMPRA_ID = @compra))
end

go
create procedure THE_CVENGERS.bajarRuta(@ruta as numeric(18,0))
as 
begin

declare @Id numeric(18,0)
declare @Compra numeric(18,0)

declare pasajesADevolver cursor
for select PASAJE_ID, PASAJE_COMPRA from THE_CVENGERS.PASAJE
	where PASAJE_DEVOLUCION IS NULL
	AND PASAJE_VIAJE_ID IN (SELECT VIAJE_ID	
							FROM THE_CVENGERS.VIAJE
							WHERE VIAJE_RUTA = @ruta
							AND VIAJE_FECHA_LLEGADA IS NULL
							AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal())


open pasajesADevolver
FETCH FROM pasajesADevolver INTO @Id, @Compra
WHILE @@FETCH_STATUS = 0
BEGIN

insert into THE_CVENGERS.DEVOLUCION (DEVOLUCION_FECHA,DEVOLUCION_NUM_COMPRA,DEVOLUCION_DESCRIPCION)
VALUES (THE_CVENGERS.fechaReal(), @Compra, 'Baja de ruta')

update THE_CVENGERS.PASAJE set PASAJE_DEVOLUCION = (select top 1 DEVOLUCION_ID FROM THE_CVENGERS.DEVOLUCION ORDER BY DEVOLUCION_ID DESC)
WHERE PASAJE_ID = @Id

UPDATE THE_CVENGERS.BUTACAXVIAJE SET BUTACAXVIAJE_PASAJE_ID = NULL
WHERE BUTACAXVIAJE_PASAJE_ID = @Id

FETCH NEXT FROM pasajesADevolver INTO @Id, @Compra 
END
CLOSE pasajesADevolver
DEALLOCATE pasajesADevolver


declare encomiendasADevolver cursor
for select ENCOMIENDA_ID, ENCOMIENDA_COMPRA from THE_CVENGERS.ENCOMIENDA
	where ENCOMIENDA_DEVOLUCION IS NULL
	AND ENCOMIENDA_VIAJE_ID IN (SELECT VIAJE_ID	
							FROM THE_CVENGERS.VIAJE
							WHERE VIAJE_RUTA = @ruta
							AND VIAJE_FECHA_LLEGADA IS NULL
							AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal())


open encomiendasADevolver
FETCH FROM encomiendasADevolver INTO @Id, @Compra
WHILE @@FETCH_STATUS = 0
BEGIN

insert into THE_CVENGERS.DEVOLUCION (DEVOLUCION_FECHA,DEVOLUCION_NUM_COMPRA,DEVOLUCION_DESCRIPCION)
VALUES (THE_CVENGERS.fechaReal(), @Compra, 'Baja de ruta')

update THE_CVENGERS.ENCOMIENDA set ENCOMIENDA_DEVOLUCION = (select top 1 DEVOLUCION_ID FROM THE_CVENGERS.DEVOLUCION ORDER BY DEVOLUCION_ID DESC)
WHERE ENCOMIENDA_ID = @Id

FETCH NEXT FROM encomiendasADevolver INTO @Id, @Compra 
END
CLOSE encomiendasADevolver
DEALLOCATE encomiendasADevolver

UPDATE THE_CVENGERS.RUTA SET RUTA_ESTADO = 0
WHERE RUTA_ID = @ruta

declare viajesACancelar cursor
for SELECT VIAJE_ID	
	FROM THE_CVENGERS.VIAJE
	WHERE VIAJE_RUTA = @ruta
	AND VIAJE_FECHA_LLEGADA IS NULL
	AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal()


open viajesACancelar
FETCH FROM viajesACancelar INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

update THE_CVENGERS.VIAJE set VIAJE_ESTADO = 0
WHERE VIAJE_ID = @Id

FETCH NEXT FROM viajesACancelar INTO @Id
END
CLOSE viajesACancelar
DEALLOCATE viajesACancelar

end

go
create procedure THE_CVENGERS.ingresarTarjeta @cli as numeric(18,0), @tipoTar as nvarchar(18), @nro as numeric(16,0),
								@cod as numeric(18,0), @fechaven as datetime
as
begin

declare @tipo numeric(18,0)
set @tipo = (select TIPO_TARJETA_ID FROM THE_CVENGERS.TIPO_TARJETA WHERE TIPO_TARJETA_DETALLE = @tipoTar)

declare @tarId numeric(18,0)
set @tarId = (select TARJETA_ID FROM THE_CVENGERS.TARJETACREDITO WHERE TARJETA_NRO = @nro
			and TARJETA_COD_SEGURIDAD = @cod AND TARJETA_FECHA_VENCIMIENTO = @fechaven 
			AND TARJETA_TIPO = @tipo)

if (@tarId is not null)
BEGIN
IF ((SELECT TARJETA_CLIENTE FROM THE_CVENGERS.TARJETACREDITO WHERE TARJETA_ID = @tarId) <> @cli)
begin
RAISERROR('La tarjeta de crédito ingresada no pertenece al cliente que está realizando la compra', 16, 1)
return
end
end
else
begin

insert into THE_CVENGERS.TARJETACREDITO (TARJETA_CLIENTE, TARJETA_TIPO, TARJETA_NRO, TARJETA_COD_SEGURIDAD, TARJETA_FECHA_VENCIMIENTO)
VALUES (@cli, @tipo, @nro, @cod, @fechaven)

END
end

go
create procedure THE_CVENGERS.crearCompraConTarjeta @user as NUMERIC(18,0), @cli as numeric(18,0), @tipoTar as nvarchar(18), @nro as numeric(16,0),
								@cod as numeric(18,0), @fechaven as datetime, @monto as numeric(18,2), @cuotas as numeric(18,0)
as
begin

declare @tipo numeric(18,0)
set @tipo = (select TIPO_TARJETA_ID FROM THE_CVENGERS.TIPO_TARJETA WHERE TIPO_TARJETA_DETALLE = @tipoTar)

DECLARE @TARJ NUMERIC(18,0)
SET @TARJ = (select TARJETA_ID FROM THE_CVENGERS.TARJETACREDITO WHERE TARJETA_NRO = @nro
			and TARJETA_COD_SEGURIDAD = @cod AND TARJETA_FECHA_VENCIMIENTO = @fechaven 
			AND TARJETA_TIPO = @tipo AND TARJETA_CLIENTE = @cli)

insert into THE_CVENGERS.COMPRA (COMPRA_USUARIO_ID, COMPRA_CLIENTE, COMPRA_TARJETA, COMPRA_CANTIDAD_DE_CUOTAS,
								COMPRA_FORMA_DE_PAGO, COMPRA_MONTO, COMPRA_FECHA)
								VALUES
								(@user, @cli, @TARJ, @cuotas, 1, @monto, THE_CVENGERS.fechaReal())
END

go
create procedure THE_CVENGERS.crearCompraConEfectivo @user as NUMERIC(18,0), @cli as numeric(18,0), @monto as numeric(18,2)
as
begin

insert into THE_CVENGERS.COMPRA (COMPRA_USUARIO_ID, COMPRA_CLIENTE, COMPRA_CANTIDAD_DE_CUOTAS,
								COMPRA_FORMA_DE_PAGO, COMPRA_MONTO, COMPRA_FECHA)
								VALUES
								(@user, @cli, 1, 0, @monto, THE_CVENGERS.fechaReal())
END

go
create procedure THE_CVENGERS.crearPasaje @cli as numeric(18,0), @viaje as numeric(18,0), @butaca as numeric(18,0)
as
begin

declare @codP numeric(18,0)
set @codP = isnull((SELECT TOP 1 PASAJE_CODIGO_PASAJE FROM THE_CVENGERS.PASAJE ORDER BY PASAJE_CODIGO_PASAJE DESC),0) + 1

declare @idButa numeric(18,0)
set @idButa = (select BUTACA_ID FROM THE_CVENGERS.BUTACA
				WHERE BUTACA_AERONAVE = (SELECT AERONAVE_ID FROM THE_CVENGERS.AERONAVE
											WHERE AERONAVE_ID = (SELECT VIAJE_AERONAVE FROM THE_CVENGERS.VIAJE
																	WHERE VIAJE_ID = @viaje))
				and BUTACA_NRO = @butaca)

declare @compra numeric(18,0)
set @compra = (SELECT TOP 1 COMPRA_ID FROM THE_CVENGERS.COMPRA ORDER BY COMPRA_ID DESC)

insert into THE_CVENGERS.PASAJE (PASAJE_CLI_ID,PASAJE_CODIGO_PASAJE, PASAJE_COMPRA, PASAJE_VIAJE_ID)
values (@cli, @codP, @compra, @viaje)
 
declare @pasaje numeric(18,0)
set @pasaje = (SELECT TOP 1 PASAJE_ID FROM THE_CVENGERS.PASAJE ORDER BY PASAJE_ID DESC)

UPDATE THE_CVENGERS.BUTACAXVIAJE SET BUTACAXVIAJE_PASAJE_ID = @pasaje
WHERE BUTACAXVIAJE_BUTACA_ID = @idButa AND BUTACAXVIAJE_VIAJE_ID = @viaje 

end

go
create procedure THE_CVENGERS.crearEncomienda @cli as numeric(18,0), @viaje as numeric(18,0), @kg as int
as
begin

declare @codE numeric(18,0)
set @codE = isnull((SELECT TOP 1 ENCOMIENDA_CODIGO FROM THE_CVENGERS.ENCOMIENDA ORDER BY ENCOMIENDA_CODIGO DESC),0) + 1


declare @compra numeric(18,0)
set @compra = (SELECT TOP 1 COMPRA_ID FROM THE_CVENGERS.COMPRA ORDER BY COMPRA_ID DESC)

insert into THE_CVENGERS.ENCOMIENDA (ENCOMIENDA_CLI_ID,ENCOMIENDA_CODIGO, ENCOMIENDA_COMPRA, ENCOMIENDA_VIAJE_ID, ENCOMIENDA_KG)
values (@cli, @codE, @compra, @viaje, @kg)
 
end

go
create function THE_CVENGERS.aeronaveConViajesPendientesEnEseLapso(@avion as numeric(18,0), @fecha as datetime)
returns int
as
BEGIN

declare @valor int

if(exists(SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA between THE_CVENGERS.fechaReal() and @fecha))
set @valor = 1
ELSE 
set @valor = 0
return @valor
END

go
create function THE_CVENGERS.aeronaveConViajesPendientes(@avion as numeric(18,0))
returns int
as
BEGIN

declare @valor int

if(exists(SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal()))
set @valor = 1
ELSE 
set @valor = 0
return @valor
END

go
create function THE_CVENGERS.aeronaveEnElAire(@avion as numeric(18,0))
returns int
as
BEGIN

declare @valor int

if(exists(SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA < THE_CVENGERS.fechaReal()))
set @valor = 1
ELSE 
set @valor = 0
return @valor
END

go
create procedure THE_CVENGERS.cancelarViaje(@viaje as numeric(18,0))
as
begin

declare @Id numeric(18,0)
declare @Compra numeric(18,0)

declare pasajesADevolver cursor
for select PASAJE_ID, PASAJE_COMPRA from THE_CVENGERS.PASAJE
	where PASAJE_DEVOLUCION IS NULL
	AND PASAJE_VIAJE_ID = @viaje


open pasajesADevolver
FETCH FROM pasajesADevolver INTO @Id, @Compra
WHILE @@FETCH_STATUS = 0
BEGIN

insert into THE_CVENGERS.DEVOLUCION (DEVOLUCION_FECHA,DEVOLUCION_NUM_COMPRA,DEVOLUCION_DESCRIPCION)
VALUES (THE_CVENGERS.fechaReal(), @Compra, 'Baja de aeronave y cancelación de viaje')

update THE_CVENGERS.PASAJE set PASAJE_DEVOLUCION = (select top 1 DEVOLUCION_ID FROM THE_CVENGERS.DEVOLUCION ORDER BY DEVOLUCION_ID DESC)
WHERE PASAJE_ID = @Id

UPDATE THE_CVENGERS.BUTACAXVIAJE SET BUTACAXVIAJE_PASAJE_ID = NULL
WHERE BUTACAXVIAJE_PASAJE_ID = @Id

FETCH NEXT FROM pasajesADevolver INTO @Id, @Compra 
END
CLOSE pasajesADevolver
DEALLOCATE pasajesADevolver


declare encomiendasADevolver cursor
for select ENCOMIENDA_ID, ENCOMIENDA_COMPRA from THE_CVENGERS.ENCOMIENDA
	where ENCOMIENDA_DEVOLUCION IS NULL
	AND ENCOMIENDA_VIAJE_ID = @viaje


open encomiendasADevolver
FETCH FROM encomiendasADevolver INTO @Id, @Compra
WHILE @@FETCH_STATUS = 0
BEGIN

insert into THE_CVENGERS.DEVOLUCION (DEVOLUCION_FECHA,DEVOLUCION_NUM_COMPRA,DEVOLUCION_DESCRIPCION)
VALUES (THE_CVENGERS.fechaReal(), @Compra, 'Baja de aeronave y cancelación de aeronave')

update THE_CVENGERS.ENCOMIENDA set ENCOMIENDA_DEVOLUCION = (select top 1 DEVOLUCION_ID FROM THE_CVENGERS.DEVOLUCION ORDER BY DEVOLUCION_ID DESC)
WHERE ENCOMIENDA_ID = @Id

FETCH NEXT FROM encomiendasADevolver INTO @Id, @Compra 
END
CLOSE encomiendasADevolver
DEALLOCATE encomiendasADevolver

update THE_CVENGERS.VIAJE set VIAJE_ESTADO = 0
WHERE VIAJE_ID = @viaje


end

go
CREATE PROCEDURE THE_CVENGERS.cancelarViajesDeAvión(@avion as numeric(18,0))
as
begin

declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal()


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

EXEC THE_CVENGERS.cancelarViaje @viaje = @Id

FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos

end

go
create function THE_CVENGERS.avionesCompatiblesFisicamente(@avion1 as numeric(18,0), @avion2 as numeric(18,0))
returns int
as
begin

declare @serv numeric(18,0)
set @serv = (select AERONAVE_SERVICIO FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion1)

declare @fabr numeric(18,0)
set @fabr = (select AERONAVE_FABRICANTE_AVION FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion1)

declare @mod nvarchar(100)
set @mod = (select AERONAVE_MODELO_AVION FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion1)

declare @espa numeric(18,0)
set @espa = (select AERONAVE_ESPACIO_ENCOMIENDAS FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion1)

declare @butac numeric(18,0)
set @butac = (select AERONAVE_CANTIDAD_BUTACAS FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion1)


declare @serv2 numeric(18,0)
set @serv2 = (select AERONAVE_SERVICIO FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion2)

declare @fabr2 numeric(18,0)
set @fabr2 = (select AERONAVE_FABRICANTE_AVION FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion2)

declare @mod2 nvarchar(100)
set @mod2 = (select AERONAVE_MODELO_AVION FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion2)

declare @espa2 numeric(18,0)
set @espa2 = (select AERONAVE_ESPACIO_ENCOMIENDAS FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion2)

declare @butac2 numeric(18,0)
set @butac2 = (select AERONAVE_CANTIDAD_BUTACAS FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_ID = @avion2)

IF(@butac=@butac2 AND @serv = @serv2 AND @fabr=@fabr2 AND @mod=@mod2 AND @espa=@espa2 AND (SELECT MAX(BUTACA_PISO) FROM THE_CVENGERS.BUTACA WHERE BUTACA_AERONAVE = @avion1)=(SELECT MAX(BUTACA_PISO) FROM THE_CVENGERS.BUTACA WHERE BUTACA_AERONAVE = @avion2))
BEGIN
IF((SELECT COUNT(*) FROM THE_CVENGERS.BUTACA WHERE BUTACA_AERONAVE = @avion1 AND BUTACA_TIPO = 'Pasillo')
	=
	(SELECT COUNT(*) FROM THE_CVENGERS.BUTACA WHERE BUTACA_AERONAVE = @avion2 AND BUTACA_TIPO = 'Pasillo'))
begin
return 1
end
else return 0
END
RETURN 0
end

go
create procedure THE_CVENGERS.aeronavePuedeReemplazarDePorVida @avion1 as numeric(18,0), @avion2 as numeric(18,0)
as
begin

if (THE_CVENGERS.avionesCompatiblesFisicamente(@avion1, @avion2) = 0)
begin
RAISERROR('No se puede reemplazar la aeronave a bajar por la aeronave seleccionada. No es compatible.',16,1)
return
end

declare @fechasa datetime
declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion1
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal()


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

set @fechasa = (SELECT VIAJE_FECHA_SALIDA FROM THE_CVENGERS.VIAJE
					WHERE VIAJE_ID = @Id) 

if (exists(SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
           WHERE VIAJE_AERONAVE = @avion2
		   AND datediff(day,VIAJE_FECHA_SALIDA, @fechasa) <= 1))
begin
RAISERROR('No se puede reemplazar la aeronave a bajar por la aeronave seleccionada. No es compatible.',16,1)
RETURN
END

FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos


end

GO
CREATE PROCEDURE THE_CVENGERS.aeronavePuedeReemplazarEsteLapso @avion1 as numeric(18,0), @avion2 as numeric(18,0),
																@fecha as datetime
as
begin

if (THE_CVENGERS.avionesCompatiblesFisicamente(@avion1, @avion2) = 0)
begin
RAISERROR('No se puede reemplazar la aeronave a bajar por la aeronave seleccionada. No es compatible.',16,1)
return
end

declare @fechasa datetime
declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion1
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA between THE_CVENGERS.fechaReal() and @fecha


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

set @fechasa = (SELECT VIAJE_FECHA_SALIDA FROM THE_CVENGERS.VIAJE
					WHERE VIAJE_ID = @Id) 

if (exists(SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
           WHERE VIAJE_AERONAVE = @avion2
		   AND datediff(day,VIAJE_FECHA_SALIDA, @fechasa) <= 1))
begin
RAISERROR('No se puede reemplazar la aeronave a bajar por la aeronave seleccionada. No es compatible.',16,1)
RETURN
END

FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos

end

GO
CREATE PROCEDURE THE_CVENGERS.cancelarViajesParaUnLapso @avion as numeric(18,0), @fecha as datetime
as
begin

declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA between THE_CVENGERS.fechaReal() and @fecha


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

EXEC THE_CVENGERS.cancelarViaje @viaje = @Id

FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos

end

go
create procedure THE_CVENGERS.suplirViaje @viaje as numeric(18,0), @avion as numeric(18,0)
as
begin

declare @Id numeric(18,0)
declare @IdBut numeric(18,0)
declare @Piso numeric(18,0)
declare @Tipo nvarchar(100)
declare @Piso1 numeric(18,0)
declare @Tipo1 nvarchar(100)

declare butacasViaje cursor
for SELECT BUTACA_ID, BUTACA_PISO, BUTACA_TIPO FROM THE_CVENGERS.BUTACA WHERE BUTACA_ID IN (select BUTACAXVIAJE_BUTACA_ID from THE_CVENGERS.BUTACAXVIAJE WHERE BUTACAXVIAJE_VIAJE_ID = @viaje)

open butacasViaje
FETCH FROM butacasViaje INTO @Id, @Piso1, @Tipo1
WHILE @@FETCH_STATUS = 0
BEGIN

declare butacasAvion cursor
for select BUTACA_ID, BUTACA_PISO, BUTACA_TIPO from THE_CVENGERS.BUTACA where BUTACA_AERONAVE = @avion order by BUTACA_NRO

open butacasAvion
FETCH FROM butacasAvion INTO @IdBut, @Piso, @Tipo
WHILE @@FETCH_STATUS = 0
BEGIN

if(not exists(select BUTACAXVIAJE_BUTACA_ID  FROM THE_CVENGERS.BUTACAXVIAJE WHERE BUTACAXVIAJE_BUTACA_ID = @IdBut AND BUTACAXVIAJE_VIAJE_ID = @viaje))
BEGIN

if(@Piso = @Piso1 and @Tipo = @Tipo1)
begin

update THE_CVENGERS.BUTACAXVIAJE set BUTACAXVIAJE_BUTACA_ID = @IdBut
where BUTACAXVIAJE_BUTACA_ID = @Id and BUTACAXVIAJE_VIAJE_ID = @viaje

end

END

FETCH NEXT FROM butacasAvion INTO @IdBut, @Piso, @Tipo
END
CLOSE butacasAvion
DEALLOCATE butacasAvion


FETCH NEXT FROM butacasViaje INTO @Id, @Piso1, @Tipo1
END
CLOSE butacasViaje
DEALLOCATE butacasViaje

update THE_CVENGERS.VIAJE set VIAJE_AERONAVE = @avion
where VIAJE_ID = @viaje

end

GO
CREATE PROCEDURE THE_CVENGERS.suplirAeronaveParaSiempre @avion1 as numeric(18,0), @avion2 as numeric(18,0)
as
begin

declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion1
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal()


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

EXEC THE_CVENGERS.suplirViaje @viaje = @Id, @avion = @avion2


FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos

end

go
CREATE PROCEDURE [THE_CVENGERS].suplirAeronaveEsteLapso @avion1 as numeric(18,0), @avion2 as numeric(18,0), @fecha as datetime
as
begin

declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion1
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA between THE_CVENGERS.fechaReal() and @fecha


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

EXEC THE_CVENGERS.suplirViaje @viaje = @Id, @avion = @avion2


FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos

end

go
CREATE PROCEDURE [THE_CVENGERS].darDeBajaVitaliciaAeronave @avion as numeric(18,0)
as
begin

update THE_CVENGERS.AERONAVE set AERONAVE_ESTADO = 0, AERONAVE_FECHA_DE_BAJA = THE_CVENGERS.fechaReal()
where AERONAVE_ID = @avion

end

go
CREATE PROCEDURE THE_CVENGERS.mandarATallerHastaFecha @avion as numeric(18,0), @fecha as datetime
as
begin

insert into THE_CVENGERS.TALLER (TALLER_AERONAVE_ID, TALLER_FECHA_ENTRADA, TALLER_FECHA_SALIDA)
VALUES (@avion, THE_CVENGERS.fechaReal(), @fecha)

end 


GO
CREATE PROCEDURE THE_CVENGERS.puedeIrATaller @avion as numeric(18,0)
as 
begin

IF(exists(select TALLER_ID FROM THE_CVENGERS.TALLER WHERE TALLER_AERONAVE_ID = @avion AND THE_CVENGERS.fechaReal() BETWEEN TALLER_FECHA_ENTRADA AND TALLER_FECHA_SALIDA))
BEGIN
RAISERROR('Esa aeronave ya se encuentra en este momento en el taller', 16, 1)
return
end

end

go
CREATE PROCEDURE THE_CVENGERS.modificarAeronave  @matri as nvarchar(100), @model as nvarchar(100), @fabricante as numeric(18,0),
												@serv as numeric(18,0), @butacas as numeric(18,0), @espacio as numeric(18,2),
												@pisos as numeric(3,0), @Id as numeric(18,0) 
as
begin

if(exists(select AERONAVE_ID FROM THE_CVENGERS.AERONAVE WHERE AERONAVE_MATRICULA_AVION = @matri and AERONAVE_ID <> @Id))
begin
raiserror('Ya existe un avión con ese número de matrícula.',16,1)
return
end

update THE_CVENGERS.AERONAVE set AERONAVE_MATRICULA_AVION = @matri, AERONAVE_CANTIDAD_BUTACAS = @butacas,
								AERONAVE_ESPACIO_ENCOMIENDAS = @espacio, AERONAVE_FABRICANTE_AVION = @fabricante,
								AERONAVE_MODELO_AVION = @model, AERONAVE_SERVICIO = @serv
where AERONAVE_ID = @Id

DELETE FROM THE_CVENGERS.BUTACA
WHERE BUTACA_AERONAVE = @Id

declare @aeronave numeric(18,0)
set @aeronave = (select AERONAVE_ID  from THE_CVENGERS.AERONAVE where AERONAVE_MATRICULA_AVION = @matri)

declare @numbut numeric(10,0)
set @numbut = 0

declare @numpiso numeric(10,0)
set @numpiso = 1

declare @butacasXpiso numeric(10,0)
set @butacasXpiso = @butacas/@pisos

declare @tipobut numeric(10,0)
set @tipobut = 0

while @numbut < @butacas
begin

if(@numbut = @butacasXpiso) set @numpiso = @numpiso + 1

insert into THE_CVENGERS.BUTACA (BUTACA_AERONAVE,BUTACA_NRO, BUTACA_PISO, BUTACA_TIPO)
values (@aeronave, @numbut, @numpiso, (case when @tipobut = 0 then 'Ventanilla' else 'Pasillo' end))

if(@tipobut = 1) set @tipobut = 0 else set @tipobut = 1
 
set @numbut = @numbut +1
end
end

go
CREATE FUNCTION THE_CVENGERS.aeronavesConMasDiasEnElTaller(@anio as int, @semestre as int)
returns table
as
return(SELECT TOP 5 AERONAVE_MATRICULA_AVION 'Matrícula de la aeronave', (SELECT ISNULL(SUM(isnull(DATEDIFF(DAY, TALLER_FECHA_ENTRADA, TALLER_FECHA_SALIDA),0)),0)
																			FROM THE_CVENGERS.TALLER
																			WHERE TALLER_AERONAVE_ID = AERONAVE_ID
																			AND ((YEAR(TALLER_FECHA_ENTRADA) = @anio AND (MONTH(TALLER_FECHA_ENTRADA) BETWEEN (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end)))
																					OR (YEAR(TALLER_FECHA_SALIDA) = @anio AND (MONTH(TALLER_FECHA_SALIDA) BETWEEN (case when @semestre = 1 then 1 else 7 end) and (case when @semestre = 1 then 6 else 12 end))))) 'Días en el taller' 
		FROM THE_CVENGERS.AERONAVE
		ORDER BY "Días en el taller" desc)
go
create FUNCTION THE_CVENGERS.aeronavePuedeReemplazarDePorVidaFunc(@avion1 as numeric(18,0), @avion2 as numeric(18,0))
RETURNS INT
as
begin

if (THE_CVENGERS.avionesCompatiblesFisicamente(@avion1, @avion2) = 0)
begin
return 0
end

declare @fechasa datetime
declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion1
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA > THE_CVENGERS.fechaReal()


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

set @fechasa = (SELECT VIAJE_FECHA_SALIDA FROM THE_CVENGERS.VIAJE
					WHERE VIAJE_ID = @Id) 

if (exists(SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
           WHERE VIAJE_AERONAVE = @avion2
		   AND datediff(day,VIAJE_FECHA_SALIDA, @fechasa) <= 1))
begin
RETURN 0
END

FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos

return 1
end

GO
CREATE function THE_CVENGERS.aeronavePuedeReemplazarEsteLapsoFunc(@avion1 as numeric(18,0), @avion2 as numeric(18,0),
																@fecha as datetime)
returns int
as
begin

if (THE_CVENGERS.avionesCompatiblesFisicamente(@avion1, @avion2) = 0)
begin
return 0
end

declare @fechasa datetime
declare @Id numeric(18,0)

DECLARE viajesFuturos CURSOR
FOR SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE WHERE VIAJE_AERONAVE = @avion1
			AND VIAJE_FECHA_LLEGADA IS NULL
			AND VIAJE_FECHA_SALIDA between THE_CVENGERS.fechaReal() and @fecha


open viajesFuturos
FETCH FROM viajesFuturos INTO @Id
WHILE @@FETCH_STATUS = 0
BEGIN

set @fechasa = (SELECT VIAJE_FECHA_SALIDA FROM THE_CVENGERS.VIAJE
					WHERE VIAJE_ID = @Id) 

if (exists(SELECT VIAJE_ID FROM THE_CVENGERS.VIAJE
           WHERE VIAJE_AERONAVE = @avion2
		   AND datediff(day,VIAJE_FECHA_SALIDA, @fechasa) <= 1))
begin
RETURN 0
END

FETCH NEXT FROM viajesFuturos INTO @Id
END
CLOSE viajesFuturos
DEALLOCATE viajesFuturos

return 1

end

go
CREATE FUNCTION THE_CVENGERS.aeronavesQuePuedenSuplantarDePorVida(@avion as numeric(18,0))
returns table
as
return(SELECT * FROM THE_CVENGERS.AERONAVE where AERONAVE_ID <> @avion AND AERONAVE_ESTADO = 1 AND
		NOT EXISTS(SELECT TALLER_ID FROM THE_CVENGERS.TALLER WHERE TALLER_AERONAVE_ID = AERONAVE_ID
					AND THE_CVENGERS.fechaReal() BETWEEN TALLER_FECHA_ENTRADA AND TALLER_FECHA_SALIDA)
		AND THE_CVENGERS.aeronavePuedeReemplazarDePorVidaFunc(@avion, AERONAVE_ID) = 1)

GO
go
CREATE FUNCTION THE_CVENGERS.aeronavesQuePuedenSuplantarPorUnLapso(@avion as numeric(18,0), @fecha as datetime)
returns table
as
return(SELECT * FROM THE_CVENGERS.AERONAVE where AERONAVE_ID <> @avion AND AERONAVE_ESTADO = 1 AND
		NOT EXISTS(SELECT TALLER_ID FROM THE_CVENGERS.TALLER WHERE TALLER_AERONAVE_ID = AERONAVE_ID
					AND THE_CVENGERS.fechaReal() BETWEEN TALLER_FECHA_ENTRADA AND TALLER_FECHA_SALIDA)
		AND THE_CVENGERS.aeronavePuedeReemplazarEsteLapsoFunc(@avion, AERONAVE_ID, @fecha) = 1)

/*DROP TABLE [THE_CVENGERS].CUOTASXTARJETA
DROP TABLE [THE_CVENGERS].MILLA
DROP TABLE [THE_CVENGERS].FECHA
DROP TABLE [THE_CVENGERS].CANJE
DROP TABLE [THE_CVENGERS].BUTACAXVIAJE
DROP TABLE [THE_CVENGERS].PRODUCTO
DROP TABLE [THE_CVENGERS].PASAJE
DROP TABLE [THE_CVENGERS].ENCOMIENDA
DROP TABLE [THE_CVENGERS].DEVOLUCION
DROP TABLE [THE_CVENGERS].COMPRA
DROP TABLE [THE_CVENGERS].BUTACA
DROP TABLE [THE_CVENGERS].TARJETACREDITO
DROP TABLE [THE_CVENGERS].TIPO_TARJETA
DROP TABLE [THE_CVENGERS].CLIENTE
DROP TABLE [THE_CVENGERS].VIAJE
DROP TABLE [THE_CVENGERS].SERVICIOXRUTA
DROP TABLE [THE_CVENGERS].RUTA
DROP TABLE [THE_CVENGERS].TALLER
DROP TABLE [THE_CVENGERS].AERONAVE
DROP TABLE [THE_CVENGERS].FABRICANTE
DROP TABLE [THE_CVENGERS].SERVICIO
DROP TABLE [THE_CVENGERS].CIUDAD
DROP TABLE [THE_CVENGERS].ROLXUSUARIO
DROP TABLE [THE_CVENGERS].USUARIO
DROP TABLE [THE_CVENGERS].FUNCIONXROL
DROP TABLE [THE_CVENGERS].ROL
DROP TABLE [THE_CVENGERS].FUNCIONALIDAD
DROP PROCEDURE [THE_CVENGERS].INIC_CLIENTE
DROP PROCEDURE [THE_CVENGERS].INIC_CIUDAD
DROP PROCEDURE [THE_CVENGERS].INIC_FABRICANTE
DROP PROCEDURE [THE_CVENGERS].INIC_SERVICIO
DROP PROCEDURE [THE_CVENGERS].INIC_AERONAVE
DROP PROCEDURE [THE_CVENGERS].INIC_RUTA
DROP PROCEDURE [THE_CVENGERS].INIC_SERVICIOXRUTA
DROP PROCEDURE [THE_CVENGERS].INIC_VIAJE
DROP PROCEDURE [THE_CVENGERS].INIC_BUTACA
DROP PROCEDURE [THE_CVENGERS].INIC_PASAJE
DROP PROCEDURE [THE_CVENGERS].INIC_ENCOMIENDA
DROP PROCEDURE [THE_CVENGERS].INIC_COMPRA
DROP PROCEDURE [THE_CVENGERS].INIC_BUTACAXVIAJE
DROP PROCEDURE [THE_CVENGERS].INIC_MILLA
DROP PROCEDURE [THE_CVENGERS].chequeoLogin
DROP PROCEDURE [THE_CVENGERS].sumarFallido
DROP PROCEDURE [THE_CVENGERS].deshabilitarUsuario
DROP PROCEDURE [THE_CVENGERS].resetearFallidos
DROP TRIGGER [THE_CVENGERS].deshabilitacionRol
DROP PROCEDURE [THE_CVENGERS].creacionRuta
DROP PROCEDURE [THE_CVENGERS].modificacionRuta
DROP VIEW [THE_CVENGERS].rutasDisponibles
DROP PROCEDURE [THE_CVENGERS].ingresoAeronave
DROP PROCEDURE [THE_CVENGERS].setearFecha
DROP FUNCTION [THE_CVENGERS].fechaReal
DROP FUNCTION [THE_CVENGERS].viajeARegistrar
DROP PROCEDURE [THE_CVENGERS].registrarLLegada
DROP PROCEDURE [THE_CVENGERS].generarViaje
DROP VIEW [THE_CVENGERS].viajesCompra
DROP PROCEDURE [THE_CVENGERS].asignarMillasViaje
DROP FUNCTION [THE_CVENGERS].destinosConMasPasajesComprados
DROP FUNCTION [THE_CVENGERS].destinosConAeronavesMasVacias
DROP FUNCTION [THE_CVENGERS].clientesConMasPuntosAcumulados
DROP FUNCTION [THE_CVENGERS].consultarMillas
DROP FUNCTION [THE_CVENGERS].calcularPrecioPasaje
DROP FUNCTION [THE_CVENGERS].calcularPrecioEncomienda
DROP PROCEDURE [THE_CVENGERS].realizarCanje
DROP FUNCTION [THE_CVENGERS].listadoMillas
DROP FUNCTION [THE_CVENGERS].listadoCanjes
DROP FUNCTION [THE_CVENGERS].comprasCliente
DROP FUNCTION [THE_CVENGERS].itemsDeCompra
DROP PROCEDURE [THE_CVENGERS].crearDevolucion
DROP PROCEDURE [THE_CVENGERS].devolverItem
DROP PROCEDURE [THE_CVENGERS].ingresarOModificarCliente
DROP FUNCTION [THE_CVENGERS].destinosConMasPasajesCancelados
DROP FUNCTION [THE_CVENGERS].tipoTarjetaCompra
DROP FUNCTION [THE_CVENGERS].numeroTarjetaCompra
DROP PROCEDURE [THE_CVENGERS].bajarRuta
DROP PROCEDURE [THE_CVENGERS].ingresarTarjeta
DROP PROCEDURE [THE_CVENGERS].crearCompraConTarjeta
DROP PROCEDURE [THE_CVENGERS].crearCompraConEfectivo
DROP PROCEDURE [THE_CVENGERS].crearPasaje
DROP PROCEDURE [THE_CVENGERS].crearEncomienda
DROP FUNCTION [THE_CVENGERS].aeronaveConViajesPendientes
DROP FUNCTION [THE_CVENGERS].aeronaveEnElAire
DROP PROCEDURE [THE_CVENGERS].cancelarViaje
DROP PROCEDURE [THE_CVENGERS].cancelarViajesDeAvión
DROP FUNCTION [THE_CVENGERS].avionesCompatiblesFisicamente
DROP PROCEDURE [THE_CVENGERS].aeronavePuedeReemplazarDePorVida
DROP PROCEDURE [THE_CVENGERS].aeronavePuedeReemplazarEsteLapso
DROP PROCEDURE [THE_CVENGERS].cancelarViajesParaUnLapso
DROP PROCEDURE [THE_CVENGERS].suplirViaje
DROP PROCEDURE [THE_CVENGERS].suplirAeronaveParaSiempre
DROP PROCEDURE [THE_CVENGERS].suplirAeronaveEsteLapso
DROP PROCEDURE [THE_CVENGERS].darDeBajaVitaliciaAeronave
DROP PROCEDURE [THE_CVENGERS].mandarATallerHastaFecha
DROP PROCEDURE [THE_CVENGERS].puedeIrATaller
DROP PROCEDURE [THE_CVENGERS].modificarAeronave
DROP FUNCTION [THE_CVENGERS].aeronavesConMasDiasEnElTaller
DROP FUNCTION [THE_CVENGERS].aeronavePuedeReemplazarDePorVidaFunc
DROP FUNCTION [THE_CVENGERS].aeronavePuedeReemplazarEsteLapsoFunc
DROP FUNCTION [THE_CVENGERS].aeronavesQuePuedenSuplantarDePorVida
DROP FUNCTION [THE_CVENGERS].aeronavesQuePuedenSuplantarPorUnLapso
DROP FUNCTION [THE_CVENGERS].aeronaveConViajesPendientesEnEseLapso
DROP PROCEDURE [THE_CVENGERS].getAll 
DROP SCHEMA [THE_CVENGERS]*/